### ISSUE TITLE
Metamos pipeline aborted at Scaffolding Step

### ISSUE THREAD

**Issue by jvollme** [marbl/metAMOS#161]
Hi, i have recently tried to run the metamos pipeline using metavelvet and soap.
Since it is a rather large metagenome that I'm assembling, I had to replace the integrated bowtie2 version with the newest version (see Issue 159), otherwise the assembly would stop at the "map-reads" step.

Problem A.) Now the pipeline progesses beyond the "mapreads"-step but aborts at the "scaffold"-step.

Could this be a similar issue (the integrated tools not being capable for very large assemblies and needing to be updated)? Which tools would I need to update/replace in this case?

Problem B.) Also there seems to have been a problem with the Metavelvet-assembly (I received a warning that the Metavelvet coverages could not be determined). However the "Assemble/out/"-Folder does contain the "meta-velvetg.Graph2-stats.txt"-File needed for determining the metavelvetg coverage peaks. Is this a problem that needs looking into, or can it probably be ignored?

here is the output including the error messages and warnings:
Starting Task = preprocess.PREPROCESS
Starting Task = assemble.ASSEMBLE
Warning: Cannot determine MetaVelvet coverages
Starting Task = mapreads.MAPREADS
Starting Task = findorfs.FINDORFS
Starting Task = validate.VALIDATE
Starting Task = findrepeats.FINDREPEATS
Starting Task = annotate.ANNOTATE
Starting Task = functionalannotation.FUNCTIONALANNOTATION
Starting Task = scaffold.SCAFFOLD
[*****************************************************************
*************************ERROR***********************************
During scaffold, the following command failed with return code -11:
>> /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/OrientContigs -minRedundancy 5 -all  -redundancy 10  -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk -repeats /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.reps 

*************************DETAILS***********************************
Last 10 commands run before the error (/home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Logs/COMMANDS.log)
|2014-10-13 23:08:56| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/toAmos_new -Q /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Preprocess/out/lib2.seq -i --min 3 --max 8040 --libname lib2 -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk 
|2014-10-13 23:32:29| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/toAmos_new -Q /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Preprocess/out/lib3.seq -i --min 2 --max 8064 --libname lib3 -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk 
|2014-10-14 00:08:46| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/toAmos_new -Q /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Preprocess/out/lib4.seq -i --min 2 --max 8021 --libname lib4 -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk 
|2014-10-14 00:26:06| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/toAmos_new -c /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Assemble/out/proba.asm.tigr -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk 
|2014-10-14 01:03:40| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/asmQC -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk -scaff -recompute -update -numsd 2 
|2014-10-14 01:03:41| perl /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/bank-unlock /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk
|2014-10-14 01:22:40| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/clk -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk
|2014-10-14 01:27:41| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/Bundler -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk
|2014-10-14 04:11:28| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/MarkRepeats -redundancy 50  -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk > /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.reps
|2014-10-14 04:50:24| /work/cluster/home/jov14/tools/metAMOS-1.5rc3_updated_bowtie2/AMOS/Linux-x86_64/bin/OrientContigs -minRedundancy 5 -all  -redundancy 10  -b /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.bnk -repeats /home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Scaffold/in/proba.reps 

Last 10 lines of output (/home/jov14/projects/mg_pm_1230/results/assemblies/141001/MetAMOS_untrimmed/Logs/SCAFFOLD.log)
FOR SKIPPED EDGE 526259 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 555580 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 555788 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 556788 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 595059 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 623470 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 695196 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 726395 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 737739 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 759471 SET EDGE STATUS TO BE 6

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************

**Comment by skoren** [comment]
Closing, inactivity.
