### ISSUE TITLE
MetaVelvet freezes at (probably) "Starting Pebble Resolution..." step

### ISSUE THREAD

**Issue by TimSkvortsov** [marbl/metAMOS#164]
Hello.

I was trying to get MetAMOS v1.5rc3 working properly under Ubuntu 14.04 LTS (64 bit, 32GB RAM) and ran into the following issue: when I try to use MetaVelvet for assembly, the whole pipeline freezes at a certain step with 100% CPU load. I suspect that this is the "Starting Pebble Resolution..." step of MetaVelevet, as it freezes at this step when used on its own (not as a part of MetAMOS).

When I use Velvet and MetaVelvet binaries compiled under Ubuntu 12.04.5 LTS using g++ v4.6.3, MetaVelevet runs perfectly both independently and as a part MetAMOS pipeline. So I suspect that the problem is somehow related to the version of g++ (g++ 4.8.2, which produces freezing meta-velvetg binaries, is used in Ubuntu 14.04 LTS).

**Comment by leonardoaj** [comment]
I faced this issue and was able to work around it on Ubuntu 16.04 by installing g++-4.7 and recompiling MetaVelvet
