### ISSUE TITLE
More automated installation problems

### ISSUE THREAD

**Issue by colinbann** [marbl/metAMOS#172]
I have similar issues to those reported in #134 Automated installation problem.  Output from 'python INSTALL.py core' below.  I am sure I have connection to internet, and I can do other installations OK, e.g:

curl -L http://psutil.googlecode.com/files/psutil-0.6.1.tar.gz -o ./psutil.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  135k  100  135k    0     0   153k      0 --:--:-- --:--:-- --:--:--  157k

Any suggestions much appreciated.
Colin

-- output from 'python INSTALL.py core' --

/cm/shared/apps/python/2.7.3/lib/python2.7/site-packages/setuptools-5.4.1-py2.7.egg/pkg_resources.py:1049: UserWarning: /panfs/panasas01.panfs.cluster/cczcb/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).

curl: (7) couldn't connect to host
tar: amos-binaries.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

curl: (7) couldn't connect to host
tar (child): stat.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Will automatically install:
        Pysam
        Setuptools
        Fastqc
        Matplotlib
        Metavelvet
        Lap
        Kronatools
        Cython
        Sra
        Velvet
        Velvet-Sc
        Kraken
        Psutil
        Uniprot
        Amos
        Numpy
Traceback (most recent call last):
  File "INSTALL.py", line 419, in <module>
    os.chdir("Statistics-Descriptive-3.0203")
OSError: [Errno 2] No such file or directory: 'Statistics-Descriptive-3.0203'

**Comment by skoren** [comment]
We've seen this issue with Krona recently but are unable to reproduce it locally. Can you make sure your INSTALL.py (or your manual installation) is downloaded the latest KronaTools version. Line 124 in INSTALL.py should be KronaTools-2.4 not 2.2 which has a syntax error on newer version of Perl.

**Comment by colinbann** [comment]
Ah - INSTALL.py does use 2.2.  I will re-try with edited version.

**Comment by skoren** [comment]
I will update the FTP files for version 2.2 to be 2.4 as well to ensure that users with an older checkout don't encounter this error.

**Comment by skoren** [comment]
Sorry for not replying earlier. The allDBs.tar file was designed to work with the frozen binary so the standard installation is not picking up it's directory structure properly. You can specify the location of the refseq_protein* files by setting the BLASTDB environment variable to the path to your blastdbs subdirectory from the extracted allDBs.tar file and metAMOS should find it then.
