### ISSUE TITLE
During mapreads, the following command failed with return code 134

### ISSUE THREAD

**Issue by shellblu** [marbl/metAMOS#175]
Hi! My MetAMOS run failed at mapreads.MAPREADS
with the following error:

*****************************************************************
*************************ERROR***********************************
During mapreads, the following command failed with return code 134:
>> /tmp/_MEIHEEhQa/Utilities/cpp/Linux-x86_64/bowtie  -p 7 -l 25 -e 140 --best --strata -m 10 -k 1 --un /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.lib1.unaligned.seq /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.IDX /home/mdavison/sortYMA/Preprocess/out/lib1.seq > /home/mdavison/sortYMA/Assemble/out/lib1.bout

*************************DETAILS***********************************
Last 10 commands run before the error (/home/mdavison/sortYMA/Logs/COMMANDS.log)
|2015-01-02 20:29:27| cat /home/mdavison/sortYMA/soapconfig.txt |grep -v max_rd_len > /home/mdavison/sortYMA/soap2config.txt
|2015-01-02 20:29:31| /tmp/_MEIHEEhQa/Utilities/cpp/Linux-x86_64/SOAPdenovo-63mer pregraph -p 7 -K 31 -R  -D   -s /home/mdavison/sortYMA/soapconfig.txt -o /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm
|2015-01-02 20:29:31| /tmp/_MEIHEEhQa/Utilities/cpp/Linux-x86_64/SOAPdenovo-63mer contig -g /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm -R  -M 3 
|2015-01-02 20:29:32| mv /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm.contig /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm.contigWIUPAC.fa
|2015-01-02 20:29:33| java -cp /tmp/_MEIHEEhQa/Utilities/java:. RemoveIUPAC /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm.contigWIUPAC.fa >/home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm.contig
|2015-01-02 20:29:33| rm /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.run
|2015-01-02 20:29:33| touch /home/mdavison/sortYMA/Assemble/out/assemble.success
|2015-01-02 20:29:35|# [MAPREADS]
|2015-01-02 20:29:39| /tmp/_MEIHEEhQa/Utilities/cpp/Linux-x86_64/bowtie-build -o 2 /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.asm.contig /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.IDX
|2015-01-02 20:29:40| /tmp/_MEIHEEhQa/Utilities/cpp/Linux-x86_64/bowtie  -p 7 -l 25 -e 140 --best --strata -m 10 -k 1 --un /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.lib1.unaligned.seq /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.IDX /home/mdavison/sortYMA/Preprocess/out/lib1.seq > /home/mdavison/sortYMA/Assemble/out/lib1.bout

Last 10 lines of output (/home/mdavison/sortYMA/Logs/MAPREADS.log)
    numLines: 15382
    ebwtTotLen: 984448
    ebwtTotSz: 984448
    reverse: 0
Total time for backward call to driver() for mirror index: 00:00:02
Reads file contained a pattern with more than 1024 sequence characters.
Please truncate reads and quality values and and re-run Bowtie.
Offending read: lib1r321/1
terminate called after throwing an instance of 'int'
/bin/bash: line 1: 15315 Aborted                 (core dumped) /tmp/_MEIHEEhQa/Utilities/cpp/Linux-x86_64/bowtie -p 7 -l 25 -e 140 --best --strata -m 10 -k 1 --un /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.lib1.unaligned.seq /home/mdavison/sortYMA/Assemble/out/soapdenovo.31.IDX /home/mdavison/sortYMA/Preprocess/out/lib1.seq > /home/mdavison/sortYMA/Assemble/out/lib1.bout
********************

**Comment by treangen** [comment]
Hi Michelle,

Looks like the error is due to bowtie1 max supported read length:

```
"Reads file contained a pattern with more than 1024 sequence characters."
```

The suggested work around would be to instead select bowtie2 as the read mapper via the supported command line parameter (-m bowtie2). Out of curiosity, are these are pacbio reads? either way, I will open an issue to indicate that bowtie2 should be the default read mapper. 

best,

**Comment by shellblu** [comment]
Sanger Reads =)

That fixed it, thanks!!!

~Michelle~



Michelle Davison
mdavison@carnegiescience.edu <mailto:mdavison@carnegiescience.edu>

~~Ο᾽τι ἐστἰ ἀγάθον ἐπίστασθαι χαλεπόν μανθάνειν~~~ 
--Under Every White Lab Coat Beats the Heart of a True Explorer--
