### ISSUE TITLE
Error during annotate task

### ISSUE THREAD

**Issue by catnais** [marbl/metAMOS#184]
Hello,

metAMOS failed to open model file during the annotate task.
I don't understand why.
I need help, please!

Here, you can find the message error : 

[Steps to be skipped]:  set(['FindRepeats'])
Starting metAMOS pipeline
Warning: Celera Assembler is not found, some functionality will not be available
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: Prokka is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: PhyloSift was not found, will not be available

Warning: EA-UTILS is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: CGAL is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
Warning: QUAST is not found, some functionality will not be available
[Available RAM: 268 GB]
	*ok
[Available CPUs: 16]
	*ok

________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Warning: Graphviz is not found, some functionality will not be available
metAMOS configuration summary:
metAMOS Version:	v1.5rc2 "Praline Brownie"  workflows: core
Time and Date:		2015-02-25
Working directory:	/home/ibmc/vittu/simData/metAMOS_run
Prefix:			proba
K-Mer:			31,51
Threads:		15
Taxonomic level:	class
Verbose:		False
Steps to skip:		MultiAlign, FunctionalAnnotation, FindRepeats, FindScaffoldORFS
Steps to force:		

[citation]
MetAMOS
	Treangen, TJ ⇔  Koren, S, Sommer, DD, Liu, B, Astrovskaya, I, Ondov, B, Darling AE, Phillippy AM, Pop, M. MetAMOS: a modular and open source metagenomic assembly and analysis pipeline. Genome biology, 14(1), R2, 2013.

Step-specific configuration:
[abundance]
MetaPhyler
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Liu B, Gibbons T, Ghodsi M, Treangen T, Pop M. Accurate and fast estimation of taxonomic profiles from metagenomic shotgun sequences. BMC Genomics. 2011;12 Suppl 2:S4. Epub 2011 Jul 27.

[multialign]
M-GCAT
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Treangen TJ, Messeguer X. M-GCAT: interactively and efficiently constructing large-scale multiple genome comparison frameworks in closely related species. BMC Bioinformatics, 2006.

[fannotate]
BLAST
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Altschul SF, Gish W, Miller W, Myers EW, Lipman DJ. Basic local alignment search tool. J Mol Biol. 1990 Oct 5;215(3):403-10.

[scaffold]
Bambus 2
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin
	Koren S, Treangen TJ, Pop M. Bambus 2: scaffolding metagenomes. Bioinformatics 27(21): 2964-2971 2011.

[findorfs]
FragGeneScan
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Rho M, Tang H, Ye Y: FragGeneScan: predicting genes in short and error-prone reads. Nucleic Acids Research 2010, 38:e191-e191.

[annotate]
FCP,Naive Bayesian Classifier
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Macdonald NJ, Parks DH, Beiko RG. Rapid identification of high-confidence taxonomic assignments for metagenomic data. Nucleic Acids Res. 2012 Apr 24.

[assemble]
Velvet
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/velvet
	Zerbino DR, Birney E. Velvet: algorithms for de novo short read assembly using de Bruijn graphs. Genome Res. 2008 May;18(5):821-9.

SOAPdenovo
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Li Y, Hu Y, Bolund L, Wang J: State of the art de novo assembly of human genomes from massively parallel sequencing data.Human genomics 2010, 4:271-277.

[mapreads]
Bowtie
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Langmead B, Trapnell C, Pop M, Salzberg SL. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 2009;10(3):R25. Epub 2009 Mar 4.

[preprocess]
metAMOS built-in filtering
	N/A

[validate]
LAP
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/LAP
	Ghodsi M, Hill CM, Astrovskaya I, Lin H, Sommer DD, Koren S, Pop M. De novo likelihood-based measures for comparing genome assemblies. BMC research notes 6:334, 2013.

[other]
Krona
	/home/ibmc/vittu/Softwares/metAMOS-1.5rc3/KronaTools/bin
	Ondov BD, Bergman NH, Phillippy AM. Interactive metagenomic visualization in a Web browser. BMC Bioinformatics. 2011 Sep 30;12:385.

Starting Task = preprocess.PREPROCESS
Starting Task = assemble.ASSEMBLE
Starting Task = mapreads.MAPREADS
Starting Task = findorfs.FINDORFS
Starting Task = validate.VALIDATE
Starting Task = findrepeats.FINDREPEATS
Starting Task = annotate.ANNOTATE
Error: parallel annotation job 0 failed

Oops, MetAMOS finished with errors! see text in red above for details.
*****************************************************************
*************************ERROR***********************************
During annotate, the following command failed with return code 255:
>> /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/nb-classify -q /home/ibmc/vittu/simData/metAMOS_run/Annotate/in/proba.asm.contig_part1.fa -m /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/models/models.txt -r /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/proba.ctg_1.nb_results.txt -e proba.ctg_1

*************************DETAILS***********************************
Last 10 commands run before the error (/home/ibmc/vittu/simData/metAMOS_run/Logs/COMMANDS.log)
|2015-02-27 02:06:33| touch /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/proba.annots
|2015-02-27 02:06:33| unlink /home/ibmc/vittu/simData/metAMOS_run/Annotate/in/proba.asm.contig
|2015-02-27 02:06:34| ln /home/ibmc/vittu/simData/metAMOS_run/Assemble/out/proba.asm.contig /home/ibmc/vittu/simData/metAMOS_run/Annotate/in/proba.asm.contig
|2015-02-27 02:06:34| unlink /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/proba.hits
|2015-02-27 02:06:34| rm -f /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/*.hits
|2015-02-27 02:06:35| rm -f /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/*.epsilon-nb_results.txt
|2015-02-27 02:06:35| rm -f /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/*.phymm.out
|2015-02-27 02:06:53| ln -s /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/models
|2015-02-27 02:06:53| ln -s /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/models/taxonomy.txt
|2015-02-27 02:06:54| /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/nb-classify -q /home/ibmc/vittu/simData/metAMOS_run/Annotate/in/proba.asm.contig_part1.fa -m /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/models/models.txt -r /home/ibmc/vittu/simData/metAMOS_run/Annotate/out/proba.ctg_1.nb_results.txt -e proba.ctg_1

Last 10 lines of output (/home/ibmc/vittu/simData/metAMOS_run/Logs/ANNOTATE.log)
unlink: cannot unlink `/home/ibmc/vittu/simData/metAMOS_run/Annotate/in/proba.asm.contig': No such file or directory
unlink: cannot unlink `/home/ibmc/vittu/simData/metAMOS_run/Annotate/out/proba.hits': No such file or directory
Determining n-mer length...
Failed to open model file: /home/ibmc/vittu/Softwares/metAMOS-1.5rc3/Utilities/models/models.txt

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************
Other error in thread 0, quitting

Thank you!

Anaïs

**Comment by treangen** [comment]
hi Anaïs,

>metAMOS failed to open model file during the annotate task.

I suspect you are missing the FCP database (and as a result, the models.txt file).  To use FCP you will need to run:

```
python INSTALL.py optional
```

This will download all necessary databases, but will take awhile to complete. Alternatively, you can switch your classifier to Kraken (-c kraken), which should be installed and available for use.

**Comment by catnais** [comment]
Hi Todd,

I install metAMOS with python INSTALL.py core nodbs.
So that's why I do not have the FCP database.
Thank you for your answer.

I think I will use Kraken.
If I launch the new command line, will it start at the annotate task or will it begin all the tasks?

Anaïs
