### ISSUE TITLE
Error in cloning into 'freebayes'....

### ISSUE THREAD

**Issue by Ramanandan** [marbl/metAMOS#192]
Dear metAMOS support team,
I am trying to install metAMOS in my machine. 
Under 2.2.3. Automated installation section of manual, when trying to install iMetAMOS run ($
python INSTALL.py iMetAMOS). I encountered the following error and pasted it for your reference **********************************
Cloning into 'freebayes'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out

mv: cannot stat ‘./freebayes’: No such file or directory
Traceback (most recent call last):
  File "INSTALL.py", line 1462, in <module>
    os.chdir("./Utilities/cpp/%s%s-%s%sfreebayes"%(os.sep, OSTYPE, MACHINETYPE, os.sep))
OSError: [Errno 2] No such file or directory: './Utilities/cpp//Linux-x86_64/freebayes'
***********************************
Also I have attached the screenshot of the error. Thanks in advance
![error in step of cloning into freebayes](https://cloud.githubusercontent.com/assets/11878969/7079642/b02d6af8-def4-11e4-9bc3-1a47fd0faca7.jpg)

**Comment by treangen** [comment]
hi Ramanandan,

This looks either like a internet connection issue on your end, possibly due to a configured firewall. I just ran the command and it successfully cloned all of the freebayes repo into the expected directory. Try running the following command :

>git clone --recursive git://github.com/ekg/freebayes.git freebayes

If it fails, try instead cloning via https:

>git clone --recursive https://github.com/ekg/freebayes.git freebayes_tmp

If this works, you can fix by searching for "git" in INSTALL.py and replace with "https". I will follow up by committing a change to v1.5rc3 INSTALL.py to use https by default.

**Comment by Ramanandan** [comment]
Hi Treangen,
Thanks for your swift response. I tried checking with the following command "git clone --recursive git://github.com/ekg/freebayes.git freebayes". I got the same error unable to connect to github.com. But I am able to clone using https. So, I changed the "git" in INSTALL.py to "https".
I have a doubt,  the installation halted at the step of cloning "freebayes".  
Do I need to run the  "$python INSTALL.py iMetAMOS" command again? or Do I need to just clone freebayes in "metAMOS-1.5rc3" folder?

**Comment by skoren** [comment]
freebayes must be cloned from github and compiled on your system. There is no way to make INSTALL.py use your clone of github so you need to either edit INSTALL.py to update the git clone command or install freebayes manually on your system and add it to your path. metAMOS will then use the one in your path.

**Comment by Ramanandan** [comment]
Thanks Dr. Serge Koren for comments.
