### ISSUE TITLE
Import error : No module named Cython.Distutils

### ISSUE THREAD

**Issue by Ramanandan** [marbl/metAMOS#193]
Dear Treangen/metAMOS support team,

You might have seen I have posted another error message regarding freebayes. I am currently installing in two machines, one in workstation and another in my local machine.

1) In workstation, while running the command "$ python INSTALL.py core", I encountered the following error message
************************************
sratoolkit.2.3.3-3-centos_linux64/schema/vdb/
sratoolkit.2.3.3-3-centos_linux64/schema/vdb/built-in.vschema
sratoolkit.2.3.3-3-centos_linux64/schema/vdb/vdb.vschema
sratoolkit.2.3.3-3-centos_linux64/README-LIBCURL.txt
Run setup.py..
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
mv: cannot stat ‘runPipeline.py’: No such file or directory
mv: cannot stat ‘initPipeline.py’: No such file or directory
***********************************
Also attached the screenshot for your reference.
![error in setup py](https://cloud.githubusercontent.com/assets/11878969/7094486/af0ff8de-df8f-11e4-838c-91e822fa6724.jpg)

2) Just to bring it to your concern, when running the same command "$ python INSTALL.py core" in my local machine, I didn't encounter the above error message. But, while running the command "$ python INSTALL.py  iMetAMOS"I got the error message for freebayes (https://github.com/marbl/metAMOS/issues/192).
Just to avoid confusion, I posted two different issues.

**Comment by skoren** [comment]
Can you check if you are able to download the cython package manually?

```
curl -L https://github.com/cython/cython/archive/master.zip -o ./cython.zip
```
If that download command does not work, this is the reason for your error. The download connection is being blocked on your system. You can manually install required metAMOS dependencies (like Cython) in these cases (the dependencies are listed here: http://metamos.readthedocs.org/en/v1.5rc3/content/installation.html).

**Comment by Ramanandan** [comment]
Dear Dr.Serge Koren,

I am able to download the cython using the above command.Then I executed the following commands
- unzip ./cython.zip
- mv ./cython-master ./Utilities/python/cython
- Next, I execute python INSTALL.py iMetAMOS
Error Message:
running build_ext
building 'matplotlib.ft2font' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_ARRAY_API -DPYCXX_ISO_CPP_LIB=1 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/usr/include -I. -I/usr/lib/python2.7/dist-packages/numpy/core/include/freetype2 -I/usr/local/include/freetype2 -I/usr/include/freetype2 -I./freetype2 -I/usr/include/python2.7 -c src/ft2font.cpp -o build/temp.linux-x86_64-2.7/src/ft2font.o
In file included from ./CXX/Extensions.hxx:37:0,
                 from src/ft2font.h:6,
                 from src/ft2font.cpp:3:
./CXX/WrapPython.h:58:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Error: cannot find MPI, required to build Ray. Please add it to your path.
Run setup.py..
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
mv: cannot stat ‘runPipeline.py’: No such file or directory
mv: cannot stat ‘initPipeline.py’: No such file or directory

**Comment by skoren** [comment]
You cannot download the package manually and place it into the metAMOS folder since it has to be compiled and added to your python environment to work properly. If you make sure you do not have a ./Utilities/python/cython folder and run INSTALL.py, what errors does it report?

If you want to install it manually, you have to download, extract, and follow the installation instructions from Cython's page:
http://docs.cython.org/src/quickstart/install.html

**Comment by Ramanandan** [comment]
Dear Sergey Koran,

Please forgive me if I am doing something silly. I am new to linux,python
and metAMOS started to work on all these a week ago.

So now what I did is

1) deleted the cython folder located in Utilities/python/
2) then I executed this command:  python INSTALL.py iMetAMOS
3) now I can see cython folder

[image: Inline image 1]

Still I get the same error.

Error message:
running install
running build
running build_py
copying lib/matplotlib/mpl-data/matplotlibrc ->
build/lib.linux-x86_64-2.7/matplotlib/mpl-data
copying lib/matplotlib/mpl-data/matplotlib.conf ->
build/lib.linux-x86_64-2.7/matplotlib/mpl-data
running build_ext
building 'matplotlib.ft2font' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2
-Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_ARRAY_API -DPYCXX_ISO_CPP_LIB=1
-I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include
-I/usr/include -I.
-I/usr/lib/python2.7/dist-packages/numpy/core/include/freetype2
-I/usr/local/include/freetype2 -I/usr/include/freetype2 -I./freetype2
-I/usr/include/python2.7 -c src/ft2font.cpp -o
build/temp.linux-x86_64-2.7/src/ft2font.o
In file included from ./CXX/Extensions.hxx:37:0,
                 from src/ft2font.h:6,
                 from src/ft2font.cpp:3:
./CXX/WrapPython.h:58:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Error: cannot find MPI, required to build Ray. Please add it to your path.
Run setup.py..
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
mv: cannot stat ‘runPipeline.py’: No such file or directory
mv: cannot stat ‘initPipeline.py’: No such file or directory

Cheers,
Ram

**Comment by Ramanandan** [comment]
Dear Sergey,

I am currently installing metAMOS in two machines, one in workstation and another in my local machine.

1) In my workstation (wenchenaafc@wenchenaafc), while running the command "$ python INSTALL.py iMetAMOS", I encountered the following  error message "ImportError: No module named Cython.Distutils".
2) In my local machine (prabhakaranra@prabhakaranra-P8, when running the same command "$ python INSTALL.py iMetAMOS" , I didn't encounter the following error message "ImportError: No module named Cython.Distutils". 

Cheers,
Ram

**Comment by skoren** [comment]
OK, that sounds like you are missing the python-dev environment on one system but no the other.  Most likely it is included by default on your local system (this varies between linux versions/distributions). You need to install the python-dev package on the workstation which will vary based on your linux version and how the system is managed. Then, remove the cython folder again and re-run python INSTALL.py.

**Comment by Ramanandan** [comment]
Thanks a lot :) Dr. Sergey Koren, after instaling python-dev on my workstation. I didn't face the above issue again
