### ISSUE TITLE
insufficient memory to build full kraken database requires at least 100gb of memory using mini db

### ISSUE THREAD

**Issue by Ramanandan** [marbl/metAMOS#196]
Dear Dr. Sergey Koren,

How do I install this full kraken database? 

Can I download and placed it manually inside Utilities/DB?

Do we need 100GB of memory to download this full kraken database?
or 
Do we need 100GB of memory to analyze our samples with the full kraken database?

![insufficient memory to build full kraken database requires at least 100gb of memory using mini db](https://cloud.githubusercontent.com/assets/11878969/7210616/6abeccf4-e521-11e4-8b1a-4b2ef68646bf.png)

Cheers,
Ram

**Comment by skoren** [comment]
Hi,

The default full Kraken database requires 100GB both to build and run efficiently. If you don't have 100GB of ram, you would be unable to load it into ram so downloading would not help:
https://ccb.jhu.edu/software/kraken/MANUAL.html

Thus unless you have access to a machine with 100GB to run/build you would be unable to use the full Kraken DB.

**Comment by Ramanandan** [comment]
Thanks Dr. Sergey Koren, then I wont be able to work on full DB with my local machine (24GB ram) and work station (64 GB ram). Then I will try with our cluster which has 1000GB of ram. But I have to get many levels of permission :(.

**Comment by skoren** [comment]
The miniature database has reasonable sensitivity and specificity so before worrying about building the full DB, you can try analyzing your datasets with the miniDB and see how it performs.

**Comment by avapirev** [comment]
Hi, in the case of insufficient RAM for the whole Kraken DB on a certain machine, is there an option to point the pipeline to a different location where the full database resides. Just for reference, there are not that many clusters with 'fat' nodes where Kraken can be built by the users, only by the admins and this option is a bottleneck for many reserchers. Most HPC systems rely on many-core architectures and do not provide enough RAM for building Kraken. For using it - yes, not building though. Thank you.
