### ISSUE TITLE
Error at Preprocess step

### ISSUE THREAD

**Issue by Ramanandan** [marbl/metAMOS#197]
Dr. Sergey Koren,

As you suggested in issue 196, I used the mini kraken DB for my analyses. 

While executing my following shell script, I received the following error for my samples.
1) I have two shotgun sample reads (forward reads - sample1_r1.fastq, reverse reads - sample1_r2.fastq).
2) please find my initPipeline and runPipeline

../initPipeline -f -1 sample1_r1.fastq -2 sample1_r2.fastq -d JSNSAMPLE1 -i 500:3500
../runPipeline -a soap -c kraken -g fraggenescan -p 15 -d JSNSAMPLE1 -k 55 -f Assemble,MapReads,FindORFS,Annotate,FunctionalAnnotation,Propagate,Classify,Abundance,FindScaffoldORFS -n FunctionalAnnotation

Please find attached my error screenshot.
![error screenshot](https://cloud.githubusercontent.com/assets/11878969/7212261/38936774-e532-11e4-9219-5dace8e3affe.png)

**Comment by Ramanandan** [comment]
Dear Dr.Sergey,

Both of my fastq reads file are 4.5Gb each. So, I tried increasing java virtual memory. Then also I am getting the same error.

Is the initpipeline in correct format for reading two reads (forward and reverse) from same sample.

Cheers,
Ram

**Comment by skoren** [comment]
The problem is you are specifying that your input files are fastq (-f on initPipeline). This is leading to the out of memory error because the program is reading until it finds a '>' to end the fasta sequence which it does not find and tries to load the entire sequence file into memory. If you change to -q from -f it should fix the issue.

**Comment by Ramanandan** [comment]
Hi Dr. Sergey,

As you suggested, I replaced -f with -q. When I executed the below shell script in my workstation  I encountered following error at Scaffold step.
******************************************************
Shell script name : JSN_sample1.1.sh
#/bin/sh
../initPipeline -q -1 S002984_r1.fastq -2 S002984_r2.fastq -d JSNSAMPLE3 -i 300:500
../runPipeline -a soap -c kraken -g fraggenescan -p 15 -d S002984_r1_sample1.1 -k 55 -f Assemble,MapReads,FindORFS,Annotate,FunctionalAnnotation,Propagate,Classify,Abundance,FindScaffoldORFS -n FunctionalAnnotation
******************************************************

wenchenaafc@wenchenaafc:~/metAMOS-1.5rc3/JSN$ ./JSN_sample1.1.sh
Error: cannot find BLAST DB directory, expected it in /home/wenchenaafc/metAMOS-1.5rc3/Utilities/DB/. Disabling blastdb dependent programs
Project dir /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1 successfully created!
Use runPipeline.py to start Pipeline
Error: cannot find BLAST DB directory, expected it in /home/wenchenaafc/metAMOS-1.5rc3/Utilities/DB/. Disabling blastdb dependent programs
Error: cannot find BLAST DB directory, expected it in /home/wenchenaafc/metAMOS-1.5rc3/Utilities/DB/. Disabling blastdb dependent programs
**no blast DB directory available, disabling steps requiring BLAST DB
[Steps to be skipped]:  set(['FunctionalAnnotation', 'FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
Starting metAMOS pipeline
Error: cannot find BLAST DB directory, expected it in /home/wenchenaafc/metAMOS-1.5rc3/Utilities/DB/. Disabling blastdb dependent programs
Warning: Celera Assembler is not found, some functionality will not be available
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: metaphylerClassify is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: PhyloSift was not found, will not be available

Warning: FRCbam is not found, some functionality will not be available
Warning: MPI is not available, some functionality may not be available
[Available RAM: 65 GB]
	*ok

________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Warning: Graphviz is not found, some functionality will not be available
metAMOS configuration summary:
metAMOS Version:	v1.5rc2 "Praline Brownie"  workflows: core,imetamos
Time and Date:		2015-04-22
Working directory:	/home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1
Prefix:			proba
K-Mer:			55
Threads:		15
Taxonomic level:	class
Verbose:		False
Steps to skip:		MultiAlign, FunctionalAnnotation, FindRepeats
Steps to force:		Abundance, FindORFS, Annotate, Propagate, MapReads, Assemble, FindScaffoldORFS, Classify

[citation]
MetAMOS
	Treangen, TJ ⇔  Koren, S, Sommer, DD, Liu, B, Astrovskaya, I, Ondov, B, Darling AE, Phillippy AM, Pop, M. MetAMOS: a modular and open source metagenomic assembly and analysis pipeline. Genome biology, 14(1), R2, 2013.


Step-specific configuration:
[abundance]
MetaPhyler
	
	Liu B, Gibbons T, Ghodsi M, Treangen T, Pop M. Accurate and fast estimation of taxonomic profiles from metagenomic shotgun sequences. BMC Genomics. 2011;12 Suppl 2:S4. Epub 2011 Jul 27.

[multialign]
M-GCAT
	/home/wenchenaafc/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Treangen TJ, Messeguer X. M-GCAT: interactively and efficiently constructing large-scale multiple genome comparison frameworks in closely related species. BMC Bioinformatics, 2006.

[fannotate]
BLAST
	/home/wenchenaafc/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Altschul SF, Gish W, Miller W, Myers EW, Lipman DJ. Basic local alignment search tool. J Mol Biol. 1990 Oct 5;215(3):403-10.

[scaffold]
Bambus 2
	/home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin
	Koren S, Treangen TJ, Pop M. Bambus 2: scaffolding metagenomes. Bioinformatics 27(21): 2964-2971 2011.

[findorfs]
FragGeneScan
	/home/wenchenaafc/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Rho M, Tang H, Ye Y: FragGeneScan: predicting genes in short and error-prone reads. Nucleic Acids Research 2010, 38:e191-e191.

[annotate]
Kraken
	/home/wenchenaafc/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin
	Wood DE, Salzberg SL: Kraken: ultrafast metagenomic sequence classification using exact alignments. Genome Biology 2014, 15:R46.

[assemble]
SOAPdenovo
	/home/wenchenaafc/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Li Y, Hu Y, Bolund L, Wang J: State of the art de novo assembly of human genomes from massively parallel sequencing data.Human genomics 2010, 4:271-277.

[mapreads]
Bowtie
	/home/wenchenaafc/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Langmead B, Trapnell C, Pop M, Salzberg SL. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 2009;10(3):R25. Epub 2009 Mar 4.

[preprocess]
metAMOS built-in filtering
	N/A

[validate]
LAP
	/home/wenchenaafc/metAMOS-1.5rc3/LAP
	Ghodsi M, Hill CM, Astrovskaya I, Lin H, Sommer DD, Koren S, Pop M. De novo likelihood-based measures for comparing genome assemblies. BMC research notes 6:334, 2013.

[other]
Krona
	/home/wenchenaafc/metAMOS-1.5rc3/KronaTools/bin
	Ondov BD, Bergman NH, Phillippy AM. Interactive metagenomic visualization in a Web browser. BMC Bioinformatics. 2011 Sep 30;12:385.


sh: 1: Syntax error: Bad fd number
Starting Task = preprocess.PREPROCESS
    Job  = [[S002984_r1.fastq, S002984_r2.fastq] -> preprocess.success] completed
Completed Task = preprocess.Preprocess
Starting Task = assemble.ASSEMBLE
    Job  = [preprocess.success -> *.run] completed
Completed Task = assemble.SplitAssemblers
    Job  = [soapdenovo.55.run -> soapdenovo.55.asm.contig] completed
Completed Task = assemble.Assemble
    Job  = [[soapdenovo.55.asm.contig] -> [assemble.ok]] completed
Completed Task = assemble.CheckAsmResults
Uptodate Task = assemble.SplitMappers
Starting Task = mapreads.MAPREADS
    Job  = [soapdenovo.55.asm.contig -> soapdenovo.55.contig.cvg] completed
Completed Task = mapreads.MapReads
    Job  = [[soapdenovo.55.contig.cvg] -> [mapreads.ok]] completed
Completed Task = mapreads.CheckMapResults
Uptodate Task = mapreads.SplitForORFs
Starting Task = findorfs.FINDORFS
    Job  = [soapdenovo.55.contig.cvg -> soapdenovo.55.faa] completed
Completed Task = findorfs.FindORFS
Starting Task = validate.VALIDATE
    Job  = [[soapdenovo.55.faa] -> [validate.ok]] completed
Completed Task = validate.Validate
Starting Task = findrepeats.FINDREPEATS
    Job  = [proba.fna -> proba.repeats] completed
Completed Task = findreps.FindRepeats
Starting Task = annotate.ANNOTATE
    Job  = [proba.faa -> proba.hits] completed
Completed Task = annotate.Annotate
Starting Task = functionalannotation.FUNCTIONALANNOTATION
    Job  = [proba.faa -> [blast.out, krona.ec.input]] completed
Completed Task = fannotate.FunctionalAnnotation
Starting Task = scaffold.SCAFFOLD
[*****************************************************************
*************************ERROR***********************************
During scaffold, the following command failed with return code -11:
>> /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/OrientContigs -minRedundancy 5 -all  -redundancy 10  -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk -repeats /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.reps 

*************************DETAILS***********************************
Last 10 commands run before the error (/home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Logs/COMMANDS.log)
|2015-04-22 08:39:50|# [SCAFFOLD]
|2015-04-22 08:39:51| rm -rf /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk
|2015-04-22 08:44:30| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/toAmos_new -Q /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Preprocess/out/lib1.seq -i --min 1 --max 2180 --libname lib1 -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk 
|2015-04-22 08:45:41| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/toAmos_new -c /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Assemble/out/proba.asm.tigr -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk 
|2015-04-22 08:48:03| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/asmQC -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk -scaff -recompute -update -numsd 2 
|2015-04-22 08:48:03| perl /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/bank-unlock /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk
|2015-04-22 08:50:03| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/clk -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk
|2015-04-22 08:51:14| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/Bundler -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk
|2015-04-22 09:03:31| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/MarkRepeats -redundancy 50  -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk > /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.reps
|2015-04-22 09:16:26| /home/wenchenaafc/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin/OrientContigs -minRedundancy 5 -all  -redundancy 10  -b /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.bnk -repeats /home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Scaffold/in/proba.reps 

Last 10 lines of output (/home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Logs/SCAFFOLD.log)
FOR SKIPPED EDGE 628693 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 666344 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 687721 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 690038 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 692427 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 702856 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 724282 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 733650 SET EDGE STATUS TO BE 6
FOR SKIPPED EDGE 737280 SET EDGE STATUS TO BE 5
FOR SKIPPED EDGE 745176 SET EDGE STATUS TO BE 6

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************
rm: cannot remove ‘/home/wenchenaafc/metAMOS-1.5rc3/JSN/S002984_r1_sample1.1/Logs/scaffold.ok’: No such file or directory
Oops, MetAMOS finished with errors! see text in red above for details.
wenchenaafc@wenchenaafc:~/metAMOS-1.5rc3/JSN$
