### ISSUE TITLE
Error with test shell script in cluster environment

### ISSUE THREAD

**Issue by nalandaatmi** [marbl/metAMOS#200]
Hi Sergey,

When I try other test shell scripts. I get the same error.

[nalanda@comp-0-12 Test]$ ./test_phylosift.sh 
Warning: BLASR is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Project dir /users/nalanda/metAMOS-1.5rc3/Test/test_phylosift successfully created!
Use runPipeline.py to start Pipeline
[Steps to be skipped]:  set(['FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
*** metAMOS running command: touch /users/nalanda/metAMOS-1.5rc3/Test/test_phylosift/Preprocess/in/carsonella_pe_filt.fna

rm: cannot remove `/users/nalanda/metAMOS-1.5rc3/Test/test_phylosift/Logs/*.ok': No such file or directory
Starting metAMOS pipeline
Found pysam in /home/nalanda/.local/lib/python2.7/site-packages/pysam-0.6-py2.7-linux-x86_64.egg/pysam/__init__.pyc
Found psutil in /home/nalanda/.local/lib/python2.7/site-packages/psutil-0.6.1-py2.7-linux-x86_64.egg/psutil/__init__.pyc
Warning: BLASR is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
[Available RAM: 830 GB]
	*ok
[Available CPUs: 80]
	*ok

________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Oops, MetAMOS finished with errors! see text in red above for details.
Traceback (most recent call last):
  File "../runPipeline", line 964, in <module>
    no_key_legend = True)
  File "/users/nalanda/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2299, in pipeline_printout_graph
    extra_data_for_signal = t_verbose_logger(0, None, runtime_data))
  File "/users/nalanda/metAMOS-1.5rc3/Utilities/ruffus/graph.py", line 1065, in graph_printout
    raise subprocess.CalledProcessError(retcode, cmd + "\n" + "\n".join([result_str, error_str]))
CalledProcessError: Command 'dot -Gsize='(11,8)'  -Tsvg < /state/partition1/tmpyzZR7P.dot

There is no layout engine support for "dot"
Perhaps "dot -c" needs to be run (with installer's privileges) to register the plugins?
' returned non-zero exit status 1
[nalanda@comp-0-12 Test]$

**Comment by skoren** [comment]
Your system has Graphviz installed and available in your path but it isn't working properly. Remove dot from your path (in which case metAMOS will run without it) or fix your dot installation (so the control flow of metAMOS can be generated).

**Comment by nalandaatmi** [comment]
Hi Sergey,
Thanks for the solution. As you suggested, I commented the below lines in runpipeline (959 -964 line).
------------------------------------------------------------------
if not utils.getFromPath("dot", "Graphviz") == "":
pipeline_printout_graph ('flowchart.svg', 'svg', [postprocess.Postprocess],no_key_legend = True).
------------------------------------------------------------------
This time I did not see that error and test pipeline executed properly.

But I could not see any charts. As per 194 issue, even I am unable to see mapreads.js and assemble.js. I did not see any errors during install.py. I tried doing now also.

**Comment by nalandaatmi** [comment]
Hi Sergey,

Can I get some updates on the above issue?

**Comment by treangen** [comment]
hi nalandaatmi, 

I think this is likely due to missing prerequisites required for matplotlib (numpy, libpng and freetype), I suspect its either libpng and/or freetype. As per Issue #194, I recommend you first try to install both and then rerun the script to see if the mapreads & assemble plots are generated.

**Comment by nalandaatmi** [comment]
Hi Treangen,

Thanks.after having the numpy file, I could see the charts in the Assemble and Mapreads.

1) I have 50 samples with paired-end reads. Do I run the pipeline one by one for each sample or Can I run multiple samples together?
