### ISSUE TITLE
Annotation error (Kraken) - Test pipeline

### ISSUE THREAD

**Issue by ricardomf** [marbl/metAMOS#204]
Dear metAMOS developers,
I am having an error while running the test suite.
I already installed the pipeline twice but the error persists.
I hope you can help me finding the solution.

Thank you for your attention,
Ricardo Figueiredo

metAMOS-1.5rc3/Test$ ./run_pipeline_test.sh 
Could not import psutil, disabling.
Could not import psutil, disabling.
Warning: Celera Assembler is not found, some functionality will not be available
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: METAVELVET is not found, some functionality will not be available
Warning: ktImportTaxonomy is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: Prokka is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: EA-UTILS is not found, some functionality will not be available
Warning: KmerGenie is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: CGAL is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
Warning: QUAST is not found, some functionality will not be available
Warning: MPI is not available, some functionality may not be available
Project dir /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1 successfully created!
Use runPipeline.py to start Pipeline
Could not import psutil, disabling.
Could not import psutil, disabling.
[Steps to be skipped]:  set(['FunctionalAnnotation', 'FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
Starting metAMOS pipeline
Could not import psutil, disabling.
Error: cannot find BLAST DB directory, expected it in /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/DB/. Disabling blastdb dependent programs
Warning: Celera Assembler is not found, some functionality will not be available
Warning: BLASR is not found, some functionality will not be available
Warning: Newbler is not found, some functionality will not be available
Warning: METAVELVET is not found, some functionality will not be available
Warning: ktImportTaxonomy is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: Prokka is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: PHmmer is not found, some functionality will not be available
Warning: EA-UTILS is not found, some functionality will not be available
Warning: KmerGenie is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: CGAL is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Warning: FreeBayes is not found, some functionality will not be available
Warning: QUAST is not found, some functionality will not be available
Warning: MPI is not available, some functionality may not be available

________________________________________
Tasks which will be run:

Task = preprocess.Preprocess
Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
metAMOS configuration summary:
metAMOS Version:	v1.5rc3 "Praline Brownie"  workflows: core
Time and Date:		2015-04-30
Working directory:	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1
Prefix:			proba
K-Mer:			55
Threads:		15
Taxonomic level:	class
Verbose:		False
Steps to skip:		MultiAlign, FunctionalAnnotation, FindRepeats
Steps to force:		Abundance, FindORFS, Annotate, Propagate, MapReads, Assemble, FindScaffoldORFS, Classify

[citation]
MetAMOS
	Treangen, TJ ⇔  Koren, S, Sommer, DD, Liu, B, Astrovskaya, I, Ondov, B, Darling AE, Phillippy AM, Pop, M. MetAMOS: a modular and open source metagenomic assembly and analysis pipeline. Genome biology, 14(1), R2, 2013.

Step-specific configuration:
[abundance]
MetaPhyler
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Liu B, Gibbons T, Ghodsi M, Treangen T, Pop M. Accurate and fast estimation of taxonomic profiles from metagenomic shotgun sequences. BMC Genomics. 2011;12 Suppl 2:S4. Epub 2011 Jul 27.

[multialign]
M-GCAT
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Treangen TJ, Messeguer X. M-GCAT: interactively and efficiently constructing large-scale multiple genome comparison frameworks in closely related species. BMC Bioinformatics, 2006.

[fannotate]
BLAST
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Altschul SF, Gish W, Miller W, Myers EW, Lipman DJ. Basic local alignment search tool. J Mol Biol. 1990 Oct 5;215(3):403-10.

[scaffold]
Bambus 2
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin
	Koren S, Treangen TJ, Pop M. Bambus 2: scaffolding metagenomes. Bioinformatics 27(21): 2964-2971 2011.

[findorfs]
FragGeneScan
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Rho M, Tang H, Ye Y: FragGeneScan: predicting genes in short and error-prone reads. Nucleic Acids Research 2010, 38:e191-e191.

[annotate]
Kraken
	
	Wood DE, Salzberg SL: Kraken: ultrafast metagenomic sequence classification using exact alignments. Genome Biology 2014, 15:R46.

[assemble]
SOAPdenovo
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Li Y, Hu Y, Bolund L, Wang J: State of the art de novo assembly of human genomes from massively parallel sequencing data.Human genomics 2010, 4:271-277.

[mapreads]
Bowtie
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
	Langmead B, Trapnell C, Pop M, Salzberg SL. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 2009;10(3):R25. Epub 2009 Mar 4.

[preprocess]
metAMOS built-in filtering
	N/A

[validate]
LAP
	/kdbio/project/metagenomics/software/metAMOS-1.5rc3/LAP
	Ghodsi M, Hill CM, Astrovskaya I, Lin H, Sommer DD, Koren S, Pop M. De novo likelihood-based measures for comparing genome assemblies. BMC research notes 6:334, 2013.

[other]
Krona
	
	Ondov BD, Bergman NH, Phillippy AM. Interactive metagenomic visualization in a Web browser. BMC Bioinformatics. 2011 Sep 30;12:385.

Starting Task = preprocess.PREPROCESS
    Job  = [[carsonella_pe_filt.fna] -> preprocess.success] completed
Completed Task = preprocess.Preprocess
Starting Task = assemble.ASSEMBLE
    Job  = [preprocess.success -> *.run] completed
Completed Task = assemble.SplitAssemblers
    Job  = [soapdenovo.55.run -> soapdenovo.55.asm.contig] completed
Completed Task = assemble.Assemble
    Job  = [[soapdenovo.55.asm.contig] -> [assemble.ok]] completed
Completed Task = assemble.CheckAsmResults
Uptodate Task = assemble.SplitMappers
Starting Task = mapreads.MAPREADS
    Job  = [soapdenovo.55.asm.contig -> soapdenovo.55.contig.cvg] completed
Completed Task = mapreads.MapReads
    Job  = [[soapdenovo.55.contig.cvg] -> [mapreads.ok]] completed
Completed Task = mapreads.CheckMapResults
Uptodate Task = mapreads.SplitForORFs
Starting Task = findorfs.FINDORFS
    Job  = [soapdenovo.55.contig.cvg -> soapdenovo.55.faa] completed
Completed Task = findorfs.FindORFS
Starting Task = validate.VALIDATE
    Job  = [[soapdenovo.55.faa] -> [validate.ok]] completed
Completed Task = validate.Validate
Starting Task = findrepeats.FINDREPEATS
    Job  = [proba.fna -> proba.repeats] completed
Completed Task = findreps.FindRepeats
Starting Task = annotate.ANNOTATE
Error: requested to run Kraken (kraken) but not available in specified location . Please check your specification and try again
*****************************************************************
*************************ERROR***********************************
During annotate, the following command failed with return code 2:
>> perl /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/perl/ImportKraken.pl  -c -i -f /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/in/proba.asm.contig /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/proba.hits:/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Assemble/out/proba.contig.cnt:class

*************************DETAILS***********************************
Last 10 commands run before the error (/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Logs/COMMANDS.log)
|2015-04-30 16:47:33| touch /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Logs/findrepeats.skip
|2015-04-30 16:47:34|# [ANNOTATE]
|2015-04-30 16:47:34| touch /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/proba.annots
|2015-04-30 16:47:34| unlink /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/in/proba.asm.contig
|2015-04-30 16:47:34| ln /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Assemble/out/proba.asm.contig /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/in/proba.asm.contig
|2015-04-30 16:47:34| unlink /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/proba.hits
|2015-04-30 16:47:34| rm -f /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/*.hits
|2015-04-30 16:47:34| rm -f /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/*.epsilon-nb_results.txt
|2015-04-30 16:47:34| rm -f /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/*.phymm.out
|2015-04-30 16:47:35| perl /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/perl/ImportKraken.pl  -c -i -f /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/in/proba.asm.contig /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/proba.hits:/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Assemble/out/proba.contig.cnt:class

Last 10 lines of output (/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Logs/ANNOTATE.log)
unlink: cannot unlink '/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/in/proba.asm.contig': No such file or directory
unlink: cannot unlink '/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Annotate/out/proba.hits': No such file or directory
Can't locate KronaTools.pm in @INC (@INC contains: /kdbio/project/metagenomics/software/metAMOS-1.5rc3/src/phylosift/lib/ /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/perl/ImportKraken.pl line 14.
BEGIN failed--compilation aborted at /kdbio/project/metagenomics/software/metAMOS-1.5rc3/Utilities/perl/ImportKraken.pl line 14.

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
*************************ERROR***********************************
*****************************************************************
rm: cannot remove '/kdbio/project/metagenomics/software/metAMOS-1.5rc3/Test/test1/Logs/annotate.ok': No such file or directory
Oops, MetAMOS finished with errors! see text in red above for details.

**Comment by treangen** [comment]
hi Ricardo,

The error output suggests that Kraken is not installed/available (but requested in the test script you've selected).

>Error: requested to run Kraken (kraken) but not available in specified location . Please check your >specification and try again

Can you provide the output from INSTALL.py along with the install parameters that were used ?

**Comment by ricardomf** [comment]
I installed the program in other place and now is running well.
Thank you for your attention.
