### ISSUE TITLE
the dir named 'scripts' not found in MetaVelvet-1.2.02.tgz

### ISSUE THREAD

**Issue by yyq410** [marbl/metAMOS#205]
Hi~
I found in the required_file_list.txt, it will check:

Utilities/cpp/Linux-x86_64/MetaVelvet/scripts/scriptEstimatedCovMulti.py
Utilities/cpp/Linux-x86_64/MetaVelvet/scripts/shuffleAndConvertSequences_fastq2fasta.py
Utilities/cpp/Linux-x86_64/MetaVelvet/scripts/shuffleSequences_fasta.pl
Utilities/cpp/Linux-x86_64/MetaVelvet/scripts/shuffleSequences_fastq.pl

but in the INSTALL.py: (lines 662)
archive = "MetaVelvet-1.2.02.tgz"
        os.system("curl -L ftp://ftp.cbcb.umd.edu/pub/data/metamos/MetaVelvet-1.2.02.tgz -o %s"%(archive))
        os.system("rm -rf ./Utilities/cpp%s%s-%s%sMetaVelvet"%(os.sep, OSTYPE, MACHINETYPE, os.sep))

in this package, it doesn't include the directory named "scripts"...

**Comment by skoren** [comment]
The required_file_list.txt is not currently used because it is not complete. I wouldn't rely on it to test the installation but instead on the test programs in Test as well as the reported available/not available programs when you start runPipeline.
