### ISSUE TITLE
INSTALL.py error：Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by zhangws119** [marbl/metAMOS#206]
Dear metAMOS developers,
I am having an error while installing metamos core
I hope you can help me finding the solution.
Thank you for your attention
James Version

 File "INSTALL.py", line 56
    print "<<Welcome to metAMOS install>>"
                                         ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by treangen** [comment]
Hello,

Looks like you are trying to run MetAMOS with python3, which is not supported. Retry with python 2.6+, this should resolve your issue.

**Comment by zhangws119** [comment]
Thanks for treangen’s help，I will try to run MetAMOS with python2
I wish to stay in touch with you.
Thanks again.
