### ISSUE TITLE
INSTALL.py error if int(version) > 1:

### ISSUE THREAD

**Issue by zhangws119** [marbl/metAMOS#208]
Dear metAMOS developers,
I am having an error while installing metamos core
I hope you can help me finding the solution.
Thank you for your attention
James Version

File "INSTALL.py", line 529, in <module>
    if int(version) > 1:
ValueError: invalid literal for int() with base 10: ''

**Comment by skoren** [comment]
The check for jellyfish is failing on your system, can you run

```
which jellyfish
jellyfish --version
jellyfish --version |awk '{print substr($NF, 1, index($NF, ".")-1)}'
```

That should give more information on which jellyfish is in your path and what version it is reporting.

**Comment by zhangws119** [comment]
Hello，skoren. 
[root@MTB ~]# jellyfish --version
jellyfish 1.1.11
[root@MTB ~]# jellyfish --version |awk '{print substr($NF, 1, index($NF, ".")-1)}'
1
[root@MTB ~]# which jellyfish
/usr/local/bin/jellyfish
[root@MTB ~]# jellyfish --version |awk '{print substr($NF, 1, index($NF, ".")-1)}'
1
[root@MTB ~]#

**Comment by zhangws119** [comment]
......

**Comment by skoren** [comment]
Based on the results of your commands, the INSTALL.py script should be working. My guess is that the environment where INSTALL.py is running is different and the built-in jellyfish is failing to return a version. As a workaround, I would suggest removing jellyfish from your path and re-running INSTALL.py. It will then download and build the appropriate version of jellyfish for Kraken.

You can try to debug the issue further by editing the INSTALL.py code and adding:

```
print "%s"%(version)
```

before the if statement.

**Comment by izaakm** [comment]
Having the same issue on my system.

I tested the problem with a quick and dirty python script, ripped from INSTALL.py:

	import os, sys, string, subprocess, distutils.util, site, glob, multiprocessing
	#add access to utils.py, for utils dir
	METAMOS_ROOT  = os.getcwd().strip()
	INITIAL_SRC   = "%s%ssrc"%(METAMOS_ROOT, os.sep)
	sys.path.append(INITIAL_SRC)
	import utils
	import workflow
	sys.path.append(utils.INITIAL_UTILS)
	
	jellyfish = utils.getFromPath("jellyfish", "Jellyfish", False)
	print "jellyfish variable = ", jellyfish
	
	version = utils.getCommandOutput("%s --version |awk '{print substr($NF, 1, index($NF, \".\")-1)}'"%(jellyfish), False)
	print "version variable, based on jellyfish variable = ", version
	
	version_jellyfish = utils.getCommandOutput("jellyfish --version |awk '{print substr($NF, 1, index($NF, \".\")-1)}'", False)
	print "hardcoded 'jellyfish --version' = ", version_jellyfish
	
Running this script produced the following:

	$ python check_jellyfish.py 
	jellyfish variable =  /home/[username]/bin
	version variable, based on jellyfish variable =  
	hardcoded 'jellyfish --version' =  1
	
i.e., "version" variable was not able to be set from the "jellyfish" variable.

**Comment by skoren** [comment]
Ah, OK I see the issue, it needs to be %s/jellyfish. I'm not sure when this bug was introduced as it was previously working.
