### ISSUE TITLE
INSTALL.py error: line627

### ISSUE THREAD

**Issue by zhangws119** [marbl/metAMOS#210]
Dear metAMOS developers,
I am having an error while installing metamos core
I hope you can help me finding the solution.
Thank you for your attention
James Version
![qq 20150513210809](https://cloud.githubusercontent.com/assets/12234002/7611139/edfd53e0-f9b4-11e4-8fab-2ec35380aada.png)

**Comment by skoren** [comment]
Hi,

It looks like your machine blocks FTP connections. metAMOS installation required unrestricted access to download files over FTP/HTTP/HTTPS. If either of those is blocked, it will have issues installing software/databases. In this case you can try the frozen binary or you can see the workaround in issue #172 but it requires editing the INSTALL.py script to modify download locations/paths.

**Comment by treangen** [comment]
Closing this issue, FTP connection is required to download & install some of the supported software packages.
