### ISSUE TITLE
MapReads results meaning 

### ISSUE THREAD

**Issue by ricardomf** [marbl/metAMOS#212]
Hi,

First of all congratulations for metAMOS! 
Could you explain the meaning of the MapReads results in the summary.html? I cannot understand the meaning of the values of the x-axis.

Thank you in advance,
Ricardo

**Comment by skoren** [comment]
Hi,

Sorry for not replying sooner. The MapReads plot is a histogram of coverage. The x-axis is the estimated coverage for contigs based on read mapping and the y-axis is the number of contigs with that coverage.
