### ISSUE TITLE
imetamos workflow issue: Error: cannot run ABySS. Required PE library but not specified. (also happens with IDBA-UD and MaSuRCA

### ISSUE THREAD

**Issue by mfossen** [marbl/metAMOS#218]
Hello,

As the title says, this happens with ABySS, IDBA-UD, and MaSuRCA, but doesn't seem to affect the other assemblers in the imetamos workflow.

I tried building ABySS from source as well to see if that was the issue (and had it replace the binaries in the metAMOS folder with the newly-built ones) and no luck. Could it be an issue with OpenMPI?

I installed OpenMPI from the Scientific Linux 7 repository, but there were some issues with getting ABySS to recognize it during compilation, could those carry over when running it?

Let me know what logs or output you'd like to see, I initialized it using `initPipeline -1 infile.fastq.gz -d testdir/ -W imetamos -i 300:500`

and ran it with `runPipeline -d testdir/`

using python 2.7.5.

Thanks

**Comment by skoren** [comment]
Hi,

Those assemblers (IDBA-UD, ABySS, and MaSuRCA) required paired-end libraries to run so if you don't specify a paired-end library they can't run. Your init command is specifying an insert size but using the -1 option (which means single-end not paired-end sequences). If you have an interleaved paired-end file, it should be specified with the -m flag:
http://metamos.readthedocs.org/en/v1.5rc3/content/quickstart.html
