### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Kyxsune** [marbl/metAMOS#222]
Hello all, sorry for the nooby problem,  I am attempting to install this under a user on a supercomputer, and have configured the system with the appropriate environment (as far as I can tell). Yet I continue to face this obscure error: 

Traceback (most recent call last):
  File "INSTALL.py", line 511, in <module>
    mem = utils.getAvailableMemory(settings)
  File "Path_to_place/bin/metAMOS-1.5rc3/src/utils.py", line 1285, in getAvailableMemory
    freemem = long(memusage[2].split("free=")[-1])+long(cacheusage)
ValueError: invalid literal for long() with base 10: ' percent=13.6'

I have searched for some answers, but turning up nothing I figure I could/should ask here. Any help would be appreciated.
Pip freeze output:

certifi==2015.4.28
Cython==0.22.1
jellyfish==0.5.0
matplotlib==1.3.1
nose==1.3.7
numpy==1.9.2
PrimerProspector===1.0.1-release
psutil==0.6.1
pyparsing==2.0.3
pysam==0.8.3
python-dateutil==2.4.2
six==1.9.0
tax2tree==1.0
tornado==4.2

Thanks again

**Comment by skoren** [comment]
This looks like psutil is returning the output in an unexpected format. Your version of 0.6.1 should be OK, unless a different one is being loaded somehow. You can run a simple test using psutil

```
import psutil

print psutil.phymem_usage()
print psutil.__file__
print psutil.__version__

cacheusage=0
memusage =  `psutil.phymem_usage()`.split(",")
freemem = long(memusage[2].split("free=")[-1])+long(cacheusage)
percentfree = float(memusage[3].split("percent=")[-1].split(")")[0])
avram = (freemem/1000000000)

print "%s %s %s"%(freemem, percentfree, avram)
```
Which should print the path to the psutil library, the version of the library, and output from the command which is failing.

**Comment by Kyxsune** [comment]
Thanks for the insight, I immediately checked the version of psutil being called by the python interpreter. You are correct, it was calling the 2.1.1 version that the shared interpreter was using, even though the environment had a version installed. I cleared the environment (preferring to do a fresh install), and detached from the shared interpreter. Fingers crossed it works out ^^

Thanks a ton for the response.
