### ISSUE TITLE
Assembly outputs

### ISSUE THREAD

**Issue by Vandervalh** [marbl/metAMOS#224]
Hello

I'm performing a metagenome assembly using metAMOS with metaIDBA and differents k-mers. I'm wondering if there is some documentation (in detail) to understand what is each file generated in the assembly step?. I know that the files are more or less the same using other assemblers, and also I saw the output part in "read the docs", but I want to understand more in depth; this is specially important if I want to compare assemblies obtained with different k-mers.

Thank you for the help

**Comment by skoren** [comment]
Most of the metAMOS generated assembly outputs are documented on the outputs page:
http://metamos.readthedocs.org/en/v1.5rc3/content/output.html

The main ones are the count of reads per contig as well as the coverage (proba.ctg.cnt and proba.ctg.cvg, respectively).  Then for each library there is the list of reads mapped to the assembly as well as the unaligned sequences (proba.lib1.contig.reads and proba.lib1.unaligned.fasta, respectively). For each assembler the proba prefix will be replaced with <assembler name>.<kmer size>. The rest of the outputs generated in Assemble/out are assembler specific so you'd have to check the documentation for each assembler to get more information.
