### ISSUE TITLE
Installtion check eror

### ISSUE THREAD

**Issue by guliseedol** [marbl/metAMOS#226]
Hi,

 I am getting this error:
~/install/metAMOS-1.5rc3/Test$ ./run_pipeline_test.sh
./run_pipeline_test.sh: line 2: ../initPipeline: No such file or directory
./run_pipeline_test.sh: line 3: ../runPipeline: No such file or directory

Though iMetaAMOS has supposedly installed properly.

Thanks in advance.

**Comment by skoren** [comment]
It appears part of the installation did not finish. Do you have the output of running python INSTALL.py on your system?

**Comment by guliseedol** [comment]
mv: cannot move `./Utilities/python/matplotlib-1.1.0' to `./Utilities/python/matplotlib/matplotlib-1.1.0': File exists
Traceback (most recent call last):
  File "INSTALL.py", line 529, in <module>
    if int(version) > 1:
ValueError: invalid literal for int() with base 10: ''

**Comment by guliseedol** [comment]
only last part of course.

**Comment by skoren** [comment]
The installation aborted at the check for Jellyfish version to install Kraken. This is similar to issue #208. I would try the workaround suggested in that ticket or checking if your version of INSTALL.py has the bug or if it was fixed.

**Comment by skoren** [comment]
Closing inactivity
