### ISSUE TITLE
Velvet always runs even when not specified

### ISSUE THREAD

**Issue by gotero** [marbl/metAMOS#228]
Hello-

Somehow when I specify only idba and spades to run as assemblers in the workflow file and on the command line, velvet still runs. Can someone suggest a solution? I can't uninstall velvet. This is the content of my workflow file:

inherit:core
programs:cmake edena ca spades idba kmergenie eautils reapr mira masurca freebayes frcbam ale cgal quast ray prokka sga abyss soap2, velvet, velvet-sc
command: -z genus -q -u -I -c kraken -a idba,spades -n FindScaffoldORFS,FunctionalAnnotation

This is how I run initPipeline:
./initPipeline -q -1 $file1.fastq -2 $file2.fastq -d $dir -W output -i 115:330

This is how I run runPipeline:
./runPipeline -t eautils -a idba,spades -d output -p 16

I get the same result (velvet runs) whether I specify the -a option or not.

Thanks!

Glen

**Comment by skoren** [comment]
Hi,

Currently in isolate mode (iMetAMOS, the -I flag in your workflow) always enables velvet. You would have to modify runPipeline to remove line 710:

```
      selected_programs["assemble"] = selected_programs["assemble"] + ",velvet"
```

I've committed  a fix to the repo as well.

**Comment by gotero** [comment]
Thanks! Figured it was something like that but couldn't find anything in the docs.
