### ISSUE TITLE
Not Preprocessing for some reason

### ISSUE THREAD

**Issue by Biomicrogen** [marbl/metAMOS#230]
Program has been working great than all of a sudden I am getting this?  Can't figure out why.  I've been running with a set of manually entered kmer values and now I'm trying to run this with an auto selected value (without entering a -k option).  Is there something I need to reset?
 
Initial command:

sudo ./initPipeline -q -1 /media/biomicrogen/U-Store-2/Processed-Seq/MiSEQ-270-PE1.fastq -2 /media/biomicrogen/U-Store-2/Processed-Seq/MiSEQ-270-PE2.fastq -c /media/biomicrogen/UBDISK/biomicrogen/BP-Trinity.fasta -d /media/biomicrogen/UBDISK/biomicrogen/runs/270-Trin -i 300:700 -W iMetAMOS 

Run Command:
sudo ./runPipeline -d /media/biomicrogen/UBDISK/biomicrogen/runs/Raw-Trin -v -o 40 -p 8 -f Scaffold -n Classify

Oops, MetAMOS finished with errors! see text in red above for details.
Traceback (most recent call last):
  File "./runPipeline", line 985, in <module>
    verbose = 1)
  File "/media/biomicrogen/UBDISK/biomicrogen/metamos/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    
    Exception #1
      'exceptions.IOError([Errno 2] No such file or directory: '/media/biomicrogen/UBDISK/biomicrogen/runs/Raw-Trin/Assemble/out/proba.kmer')' raised in ...
       Task = def assemble.SplitAssemblers(...):
       Job  = [preprocess.success -> *.run]
    
    Traceback (most recent call last):
      File "/media/biomicrogen/UBDISK/biomicrogen/metamos/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/media/biomicrogen/UBDISK/biomicrogen/metamos/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/media/biomicrogen/UBDISK/biomicrogen/metamos/src/assemble.py", line 293, in SplitAssemblers
        stats = open("%s/Assemble/out/%s.kmer"%(_settings.rundir, _settings.PREFIX), 'w')
    IOError: [Errno 2] No such file or directory: '/media/biomicrogen/UBDISK/biomicrogen/runs/Raw-Trin/Assemble/out/proba.kmer'

**Comment by skoren** [comment]
Hi,

When you let metAMOS auto-set a k-mer it relies on KmerGenie which has some dependences metAMOS doesn't install (R and required packages). I think there is a bug in the code where if it cannot run kmergenie it will give the error you are seeing rather than defaulting to k=31. Can you check the ASSEMBLE.log for error messages? There should also be a command to run KmerGenie in COMMANDS.log.

**Comment by skoren** [comment]
Closing, inactivity.
