### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by sejmodha** [marbl/metAMOS#233]
Hi there,

I have recently encountered a segmentation fault error with metAMOS. I am using the latest version of the pipeline since last update but have come across the following problem at MAPREADS step since last few days.
Any help would be appreciated.

**\* metAMOS running command: /usr/bin/bowtie2 -p 12 -D 15 -R 2 -N 0 -L 20 -i S,1,1.10 --un ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.seq -x ~/output_dir/Assemble/out/soapdenovo2.31.IDX ~/output_dir/Preprocess/out/lib1.seq -S ~/output_dir/Assemble/out/lib1.sam

**\* metAMOS running command: java -cp /home1/modh01s/metAMOS-1.5rc3/Utilities/java:. convertFastqToFasta ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.seq ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.fasta ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.fasta.qual

Segmentation fault

**Comment by skoren** [comment]
Could you send the output in ASSEMBLE.log in the log folder?

**Comment by sejmodha** [comment]
Here it is:
/usr/bin/mpirun -np 12 ABYSS-P -k31 -q3    --coverage-hist=coverage.hist -s abyss.31-bubbles.fa  -o abyss.31-1.fa ~/output_dir/Preprocess/out/lib1.1.fastq ~/output_dir/Preprocess/out/lib1.2.fastq 

## 12 total processes failed to start

mpirun was unable to launch the specified application as it could not find an executable:

Executable: ABYSS-P
Node: Alpha

## while attempting to start process rank 0.

make: **\* [abyss.31-1.fa] Error 133
unlink: cannot unlink ‘~/output_dir/Assemble/out/abyss.31.asm.contig’: No such file or directory
ln: failed to access ‘~/output_dir/Assemble/out/abyss.31-contigs.fa’: No such file or directory

Version 2.04: released on July 13th, 2012
Compile Jul  9 2013 11:57:16

---

Pregraph

---

Parameters: pregraph -p 12 -K 31 -R -s ~/output_dir/soap2config.txt -o ~/output_dir/Assemble/out/soapdenovo2.31.asm 

In ~/output_dir/soap2config.txt, 1 lib(s), maximum read length 100, maximum name length 256.

12 thread(s) initialized.
Import reads from file:
 ~/output_dir/Preprocess/out/lib1.1.fastq
Import reads from file:
 ~/output_dir/Preprocess/out/lib1.2.fastq
Time spent on hashing reads: 9s, 650448 read(s) processed.
LIB(s) information:
 [LIB] 0, avg_ins 225, reverse 0.
2351824 node(s) allocated, 45421430 kmer(s) in reads, 45421430 kmer(s) processed.
done hashing nodes
2229589 linear node(s) marked.
Time spent on marking linear nodes: 0s.
Time spent on pre-graph construction: 10s.

Start to remove frequency-one-kmer tips shorter than 62.
Total 36084 tip(s) removed.
12 thread(s) initialized.
18542 linear node(s) marked.
Start to remove tips with minority links.
3916 tip(s) removed in cycle 1.
5 tip(s) removed in cycle 2.
0 tip(s) removed in cycle 3.
Total 3921 tip(s) removed.
12 thread(s) initialized.
0 linear node(s) marked.
Time spent on removing tips: 5s.

195505 (97768) edge(s) and 24017 extra node(s) constructed.
Time spent on constructing edges: 4s.

In file: ~/output_dir/soap2config.txt, max seq len 100, max name len 256.
12 thread(s) initialized.
Import reads from file:
 ~/output_dir/Preprocess/out/lib1.1.fastq
Import reads from file:
 ~/output_dir/Preprocess/out/lib1.2.fastq
650448 read(s) processed.
Time spent on:
 importing reads: 0s,
 chopping reads to kmers: 0s,
 searching kmers: 0s,
 aligning reads to edges: 0s,
 searching (K+1)mers: 0s,
 adding pre-arcs: 0s,
 recording read paths: 0s.
39970874 marker(s) output.
Reads alignment done, 2580 read(s) deleted, 176721 pre-arc(s) added.
LIB(s) information:
 [LIB] 0, avg_ins 225, reverse 0.
Time spent on aligning reads: 11s.

66302 vertex(es) output.
Overall time spent on constructing pre-graph: 0m.

Version 2.04: released on July 13th, 2012
Compile Jul  9 2013 11:57:16

---

Contig

---

Parameters: contig -g ~/output_dir/Assemble/out/soapdenovo2.31.asm -R -M 3 

There are 66302 kmer(s) in vertex file.
There are 195505 edge(s) in edge file.
Kmers sorted.
195505 edge(s) input.
255650 pre-arcs loaded.
1213334 markers overall.
1213334 markers loaded.
49075 none-palindrome edge(s) swapped, 0 palindrome edge(s) processed.
195505 edge(s) sorted.
Arcs sorted.
967 repeat(s) are solvable, 1936 more edge(s).
3872 dead arc(s) removed.
Time spent on solving repeat: 0s.
Start to pinch bubbles, cutoff 0.100000, MAX NODE NUM 30, MAX DIFF NUM 10.
7830 start points, 169088 dheap nodes.
63819 pair(s) found, 14100 pair of path(s) compared, 7294 pair(s) merged.
Sequence comparison failed:
 Path crossing deleted edge                         0
 Length difference of two paths greater than two    1071
 Mismatch score greater than cutoff (10)             46
 Mismatch score ratio greater than cutoff (0.1)     238
 Path length shorter than (Kmer-1)                  5451
DFibHeap: 42120 node(s) allocated.
10663 edge(s) concatenated in cycle 1.
160 edge(s) concatenated in cycle 2.
0 edge(s) concatenated in cycle 3.
Time spent on pinching bubbles: 3s.
Start to destroy weak inner edges.
11116 weak inner edge(s) destroyed in cycle 1.
135 weak inner edge(s) destroyed in cycle 2.
0 weak inner edge(s) destroyed in cycle 3.
22124 dead arc(s) removed.
5409 inner edge(s) with coverage lower than or equal to 1 destroyed.
10955 dead arc(s) removed.
10720 edge(s) concatenated in cycle 1.
157 edge(s) concatenated in cycle 2.
0 edge(s) concatenated in cycle 3.
Before compacting, 197441 edge(s) existed.
After compacting, 85197 edge(s) left.

Strict: 0, cutoff length: 62.
6663 tips cut in cycle 1.
212 tips cut in cycle 2.
46 tips cut in cycle 3.
46 tips cut in cycle 4.
28 tips cut in cycle 5.
18 tips cut in cycle 6.
13 tips cut in cycle 7.
6 tips cut in cycle 8.
7 tips cut in cycle 9.
8 tips cut in cycle 10.
2 tips cut in cycle 11.
4 tips cut in cycle 12.
6 tips cut in cycle 13.
3 tips cut in cycle 14.
13 tips cut in cycle 15.
4 tips cut in cycle 16.
1 tips cut in cycle 17.
0 tips cut in cycle 18.
5759 dead arc(s) removed.
1924 edge(s) concatenated in cycle 1.
6 edge(s) concatenated in cycle 2.
0 edge(s) concatenated in cycle 3.
Before compacting, 85197 edge(s) existed.
After compacting, 67177 edge(s) left.

There are 7378 contig(s) longer than 100, sum up 754448 bp, with average length 102.
The longest length is 804 bp, contig N50 is 100 bp,contig N90 is 100 bp.
33458 contig(s) longer than 32 output.

Time spent on constructing contig: 0m.

Processing file ~/output_dir/Assemble/out/soapdenovo2.31.asm.contigWIUPAC.fa

**Comment by skoren** [comment]
Do you have a MAPREADS.log file as well?

**Comment by sejmodha** [comment]
MAPREADS.log output:

650448 reads; of these:
  650448 (100.00%) were unpaired; of these:
    648166 (99.65%) aligned 0 times
    2253 (0.35%) aligned exactly 1 time
    29 (0.00%) aligned >1 times
0.35% overall alignment rate

**Comment by sejmodha** [comment]
The pipeline seems to fail at this command regardless of any assembler is chosen for the assembly as .mappedmates file is not created. Following is an example using idba-ud
cat ~/output_dirAssemble/out/idba-ud.31.lib1.mappedmates >> ~/output_dirAssemble/out/idba-ud.31.lib1.hdr

**Comment by skoren** [comment]
What happens if you run the command manually:
java -cp /home1/modh01s/metAMOS-1.5rc3/Utilities/java:. convertFastqToFasta ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.seq ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.fasta ~/output_dir/Assemble/out/soapdenovo2.31.lib1.unaligned.fasta.qual

It could be an issue with the JVM configuration on the system.

**Comment by sejmodha** [comment]
Java command on its own runs fine without any errors.

Sej

**Comment by skoren** [comment]
In that case it seems the crash is in the PySam library parsing the output of bowtie2. Can you verify the sam file looks well-formmated and can be parsed by samtools (e.g. samtools view or similar)? You could also try switching to bowtie from bowtie2 as that uses a different output/parsing format.

**Comment by sejmodha** [comment]
I've tried with bowtie and bowtie2 and I get exact same error with both
tools.

**Comment by sejmodha** [comment]
I figured it's nothing to do with bowtie or bowtie2 but it's something to do with how mate-pair libraries are specified in metAMOS. As the error occurs because mateheaderfile .hdr and .mappedmates files are not generated. Would you think it's something to do with following commads in the mapreads.py files that is the cause of this problem?

 mateheader = open("%s/Assemble/out/%s.lib%d.hdr"%(_settings.rundir,_settings.PREFIX,lib.id),'w')
        new_matefile = open("%s/Assemble/out/%s.lib%d.mappedmates"%(_settings.rundir,_settings.PREFIX,lib.id),'w')
        badmatefile = open("%s/Assemble/out/%s.lib%d.badmates"%(_settings.rundir,_settings.PREFIX,lib.id),'w')
        ctgmatefile = open("%s/Assemble/out/%s.lib%d.mates_in_diff_contigs"%(_settings.rundir,_settings.PREFIX,lib.id),'w')
        updatedinserts = open("%s/Assemble/out/%s.lib%d.meanstdev"%(_settings.rundir, _settings.PREFIX, lib.id), 'w')

**Comment by skoren** [comment]
Based on your output, almost none of the sequences mapped so I'm guessing there were no pairs in the tiny fraction of reads which could be mapped. Either the assembly is fragmented or very low quality to cause this or the estimate for the pair separation is not correct. 

metAMOS parses the output to get correctly mapped mates from the bowtie/bowtie2 output.However, the files should just end up as empty. It's still not clear where the error comes from since python shouldn't segfault.

Do you get the same error if you specify the library as unpaired?

**Comment by sejmodha** [comment]
Hi,
I initially thought it was a sample specific problem but I tried the pipeline with other samples and also tried the test_bowtie2.sh script that terminated with exact same segmentation fault error.

**Comment by sejmodha** [comment]
Additionally, the pipeline works fine with default parameters for any samples but terminates with segmentation fault with customised parameters.

**Comment by skoren** [comment]
I've verified that test_bowtie2.sh works on my local installation and it falling on your system would support my original guess that there was an issue with pysam parsing the output. I'm not sure why it would fail with bowtie as well in that case. Are you able to share your dataset?

I'm not sure what you mean by "customized" parameters. Most of the scripts in Test change the parameters (assemblers, gene caller, classifier) and run with a variety of inputs/insert sizes. If you have specific examples of configurations which work and don't you can post them.

**Comment by sejmodha** [comment]
Yes, you are right, it is an issue with PySAM. Bowtie works fine after re-building the pipeline but bowtie2 still does not work. I have re-installed pysam's latest version that was already installed on my machine but I still get the segmentation fault error when using bowtie2 as mapper in the pipeline with -m parameter.

**Comment by sejmodha** [comment]
I have managed to fix bowtie2 and pysam parsing issue by installing pysam 0.6. 
Following pysam installation commands specified in INSTALL.py script seems to fix the problem when pysam-0.6 is installed within metAMOS in Utilities/python folder

wget http://pysam.googlecode.com/files/pysam-0.6.tar.gz -o ./pysam.tar.gz")
tar -C ./Utilities/python -xvf pysam.tar.gz
mv ./Utilities/python/pysam-0.6 ./Utilities/python/pysam
sudo python ./Utilities/python/pysam/setup.py install

Thanks for your help once again.

**Comment by skoren** [comment]
Closing, inactivity
