### ISSUE TITLE
metAMOS failed with return code -9

### ISSUE THREAD

**Issue by osnattirosh** [marbl/metAMOS#239]
Hi,
The error seem to occur in the annotation step. this is from the job log:
Job  = [[1085_notbac3.1.fastq, 1085_notbac3.2.fastq] -> preprocess.success] completed
Completed Task = preprocess.Preprocess
    Job  = [preprocess.success -> *.run] completed
Completed Task = assemble.SplitAssemblers
    Job  = [soapdenovo.55.run -> soapdenovo.55.asm.contig] completed
Completed Task = assemble.Assemble
    Job  = [[soapdenovo.55.asm.contig] -> [assemble.ok]] completed
Completed Task = assemble.CheckAsmResults
Uptodate Task = assemble.SplitMappers
    Job  = [soapdenovo.55.asm.contig -> soapdenovo.55.contig.cvg] completed
Completed Task = mapreads.MapReads
    Job  = [[soapdenovo.55.contig.cvg] -> [mapreads.ok]] completed
Completed Task = mapreads.CheckMapResults
Uptodate Task = mapreads.SplitForORFs
    Job  = [soapdenovo.55.contig.cvg -> soapdenovo.55.faa] completed
Completed Task = findorfs.FindORFS
    Job  = [[soapdenovo.55.faa] -> [validate.ok]] completed
Completed Task = validate.Validate
    Job  = [proba.fna -> proba.repeats] completed
Completed Task = findreps.FindRepeats
Starting Task = preprocess.PREPROCESS
Starting Task = assemble.ASSEMBLE
Starting Task = mapreads.MAPREADS
Starting Task = findorfs.FINDORFS
Starting Task = validate.VALIDATE
Starting Task = findrepeats.FINDREPEATS
Starting Task = annotate.ANNOTATE
rm: cannot remove `/data/tirosho/metAMOS5/Logs/annotate.ok': No such file or directory
Error: parallel annotation job 0 failed

Oops, MetAMOS finished with errors! see text in red above for details.

---

************************_ERROR**_********************************
During annotate, the following command failed with return code -9:

> > python /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/python/NB-BL.py /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.nb_results.txt /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.bl_results.txt /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.intermediate.epsilon-nb_results.txt

************************_DETAILS**_********************************
Last 10 commands run before the error (/data/tirosho/metAMOS5/Logs/COMMANDS.log)
|2016-02-23 21:05:56| unlink /data/tirosho/metAMOS5/Annotate/out/proba.hits
|2016-02-23 21:05:57| rm -f /data/tirosho/metAMOS5/Annotate/out/_.hits
|2016-02-23 21:05:58| rm -f /data/tirosho/metAMOS5/Annotate/out/_.epsilon-nb_results.txt
|2016-02-23 21:05:58| rm -f /data/tirosho/metAMOS5/Annotate/out/*.phymm.out
|2016-02-23 21:06:08| ln -s /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/models
|2016-02-23 21:06:08| ln -s /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/models/taxonomy.txt
|2016-02-23 21:21:00| /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/nb-classify -q /data/tirosho/metAMOS5/Annotate/in/proba.asm.contig_part1.fa -m /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/models/models.txt -r /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.nb_results.txt -e proba.ctg_1
|2016-02-23 21:21:01| ln -s /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/DB//blast_data blast_data
|2016-02-24 03:49:11| /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/blastn -query /data/tirosho/metAMOS5/Annotate/in/proba.asm.contig_part1.fa -out  /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.bl_results.txt -db /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/DB//blast_data/BacteriaAndArchaeaGenomesDB -evalue 10 -outfmt 7 -task blastn -num_threads 16
|2016-02-24 03:51:20| python /spin1/sys2/usrlocal/apps/metAMOS/metAMOS-1.5rc3/Utilities/python/NB-BL.py /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.nb_results.txt /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.bl_results.txt /data/tirosho/metAMOS5/Annotate/out/proba.ctg_1.intermediate.epsilon-nb_results.txt

Last 10 lines of output (/data/tirosho/metAMOS5/Logs/ANNOTATE.log)
  Applying models to query sequences:  0 200 400 600 800 1000 1200 1400 1600 1800 2000
  Writing out classification results.

Batch #7
  Calculating n-mers in query fragment: ....
  Applying models to query sequences:  0 200 400 600 800 1000 1200 1400 1600 1800 2000
  Writing out classification results.

Building results file: .......
Done.

Please veryify input data and restart MetAMOS. If the problem persists please contact the MetAMOS development team.
************************_ERROR**_********************************

---

Other error in thread 0, quitting

I get this with another set of data. is it a memory issue? thanks!

**Comment by skoren** [comment]
This looks like an FCP bug, have you tried using kraken instead as the classifier?

**Comment by osnattirosh** [comment]
not yet, I'll give it a try. thanks!

**Comment by skoren** [comment]
Closed, inactivity
