### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cached_phymem'

### ISSUE THREAD

**Issue by ghost** [marbl/metAMOS#241]
Hi 

I am trying to install metAMOS but ran into this error:

~/software/metAMOS-1.5rc3> python INSTALL.py core
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Will automatically install:
        Pysam
        Setuptools
        Fastqc
        Matplotlib
        Metavelvet
        Lap
        Kronatools
        Cython
        Sra
        Velvet
        Velvet-Sc
        Kraken
        Psutil
        Uniprot
        Amos
        Numpy
Traceback (most recent call last):
  File "INSTALL.py", line 511, in <module>
    mem = utils.getAvailableMemory(settings)
  File "/nfs/homeserver/phylosopher/u/ksoh/software/metAMOS-1.5rc3/src/utils.py", line 1283, in getAvailableMemory
    cacheusage = psutil.cached_phymem()
AttributeError: 'module' object has no attribute 'cached_phymem'

**Comment by treangen** [comment]
hi kengcher,

Are you running on OSX or Linux?

**Comment by mukul1992** [comment]
Hi,

I am also hitting the same error, I guess because 'cached_phymem' may be deprecated. This is on Linux CentOS 6.7. Is there a workaround?

**Comment by mukul1992** [comment]
Temporarily uninstalling psutil works as then metAMOS install script downloads and use its own compatible version.

**Comment by skoren** [comment]
metAMOS has only been tested with a specific psutil version, the next release should update to the most recent version. Closing as workaround is to let metAMOS install compatible version.

**Comment by mhibberd** [comment]
Hey All,
I realize this issue has been closed, but I'm still experiencing troubles with the psutil version. The stated version of psutil for metAMOS is 0.6.1, although the above messages suggest there would have been an update to accommodate newer versions. I'm on psutil 3.4.2 and am seeing the "cached_phymem" error at runtime with runPipeline.
Any suggestions? I'm on a cluster environment so changing the psutil version backward is slightly less trivial than on a local system.
Thanks!

**Comment by dvera** [comment]
You could try installing your own copy of python and changing your PATH to use your version.

**Comment by hiraksarkar** [comment]
Just to comment that this issue is not resolved and the version of psutil currently in use should be mentioned in the required versions in README page.

**Comment by skoren** [comment]
The version requirements are documented: http://metamos.readthedocs.io/en/v1.5rc3/content/installation.html
