### ISSUE TITLE
Error while running the iMetAOS test_pipeline_test.sh

### ISSUE THREAD

**Issue by SabeenR** [marbl/metAMOS#249]
Hi,
I've installed MetAMOS and iMetAMOS on my linux box and tried to run the test pipleine (run_pipeline_test.sh) and got the following warnings and errors:

A few questions:
1) I HAVE definitely installed MetaGeneMark, REAPR and FRC_Align I've included the executable (and bin directories) in PATH but the test scrip still cannot find them.

2) I'm not sure why the test stopped abruptly at POSTPROCESSING.

3) How can I re-run the test pipeline cleanly ? 

---

```
[root@tcmc_sandbox2 Test]# ./run_pipeline_test.sh 
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
Project directory already exists, please specify another
Alternatively, use runPipeline to run an existing project
[Steps to be skipped]:  set(['FunctionalAnnotation', 'FindRepeats'])
Starting Task = runpipeline.RUNPIPELINE
Starting metAMOS pipeline
Warning: Newbler is not found, some functionality will not be available
Warning: MetaGeneMark is not found, some functionality will not be available
Warning: SignalP+ is not found, some functionality will not be available
Warning: ALE is not found, some functionality will not be available
Warning: REAPR is not found, some functionality will not be available
Warning: FRCbam is not found, some functionality will not be available
[Available RAM: 64 GB]
        *ok
[Available CPUs: 32]
        *ok

________________________________________
Tasks which will be run:

Task = assemble.SplitAssemblers
Task = assemble.Assemble
Task = assemble.CheckAsmResults
Task = assemble.SplitMappers
Task = mapreads.MapReads
Task = mapreads.CheckMapResults
Task = mapreads.SplitForORFs
Task = findorfs.FindORFS
Task = validate.Validate
Task = findreps.FindRepeats
Task = annotate.Annotate
Task = fannotate.FunctionalAnnotation
Task = scaffold.Scaffold
Task = findscforfs.FindScaffoldORFS
Task = abundance.Abundance
Task = propagate.Propagate
Task = classify.Classify
Task = postprocess.Postprocess
________________________________________
Warning: Graphviz is not found, some functionality will not be available
metAMOS configuration summary:
metAMOS Version:        v1.5rc3 "Praline Brownie"  workflows: core,optional
Time and Date:          2016-09-23
Working directory:      /home/AnalysisTools/metAMOS-1.5rc3/Test/test1
Prefix:                 proba
K-Mer:                  55
Threads:                15
Taxonomic level:        class
Verbose:                False
Steps to skip:          MultiAlign, FunctionalAnnotation, FindRepeats
Steps to force:         Abundance, FindORFS, Annotate, Propagate, MapReads, Assemble, FindScaffoldORFS, Classify

[citation]
MetAMOS
        Treangen, TJ â  Koren, S, Sommer, DD, Liu, B, Astrovskaya, I, Ondov, B, Darling AE, Phillippy AM, Pop, M. MetAMOS: a modular and open source metagenomic assembly and analysis pipeline. Genome biology, 14(1), R2, 2013.


Step-specific configuration:
[abundance]
MetaPhyler
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Liu B, Gibbons T, Ghodsi M, Treangen T, Pop M. Accurate and fast estimation of taxonomic profiles from metagenomic shotgun sequences. BMC Genomics. 2011;12 Suppl 2:S4. Epub 2011 Jul 27.

[multialign]
M-GCAT
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Treangen TJ, Messeguer X. M-GCAT: interactively and efficiently constructing large-scale multiple genome comparison frameworks in closely related species. BMC Bioinformatics, 2006.

[fannotate]
BLAST
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Altschul SF, Gish W, Miller W, Myers EW, Lipman DJ. Basic local alignment search tool. J Mol Biol. 1990 Oct 5;215(3):403-10.

[scaffold]
Bambus 2
        /home/AnalysisTools/metAMOS-1.5rc3/AMOS/Linux-x86_64/bin
        Koren S, Treangen TJ, Pop M. Bambus 2: scaffolding metagenomes. Bioinformatics 27(21): 2964-2971 2011.

[findorfs]
FragGeneScan
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Rho M, Tang H, Ye Y: FragGeneScan: predicting genes in short and error-prone reads. Nucleic Acids Research 2010, 38:e191-e191.

[annotate]
Kraken
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/kraken/bin
        Wood DE, Salzberg SL: Kraken: ultrafast metagenomic sequence classification using exact alignments. Genome Biology 2014, 15:R46.

[assemble]
SOAPdenovo
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Li Y, Hu Y, Bolund L, Wang J: State of the art de novo assembly of human genomes from massively parallel sequencing data.Human genomics 2010, 4:271-277.

[mapreads]
Bowtie
        /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64
        Langmead B, Trapnell C, Pop M, Salzberg SL. Ultrafast and memory-efficient alignment of short DNA sequences to the human genome. Genome Biol. 2009;10(3):R25. Epub 2009 Mar 4.

[preprocess]
metAMOS built-in filtering
        N/A

[validate]
LAP
        /home/AnalysisTools/metAMOS-1.5rc3/LAP
        Ghodsi M, Hill CM, Astrovskaya I, Lin H, Sommer DD, Koren S, Pop M. De novo likelihood-based measures for comparing genome assemblies. BMC research notes 6:334, 2013.

[other]
Krona
        /home/AnalysisTools/metAMOS-1.5rc3/KronaTools/bin
        Ondov BD, Bergman NH, Phillippy AM. Interactive metagenomic visualization in a Web browser. BMC Bioinformatics. 2011 Sep 30;12:385.


Starting Task = assemble.ASSEMBLE
    Job  = [preprocess.success -> *.run] completed
Completed Task = assemble.SplitAssemblers
    Job  = [soapdenovo.55.run -> soapdenovo.55.asm.contig] completed
Completed Task = assemble.Assemble
    Job  = [[soapdenovo.55.asm.contig] -> [assemble.ok]] completed
Completed Task = assemble.CheckAsmResults
Uptodate Task = assemble.SplitMappers
Starting Task = mapreads.MAPREADS
    Job  = [soapdenovo.55.asm.contig -> soapdenovo.55.contig.cvg] completed
Completed Task = mapreads.MapReads
    Job  = [[soapdenovo.55.contig.cvg] -> [mapreads.ok]] completed
Completed Task = mapreads.CheckMapResults
Uptodate Task = mapreads.SplitForORFs
Starting Task = findorfs.FINDORFS
    Job  = [soapdenovo.55.contig.cvg -> soapdenovo.55.faa] completed
Completed Task = findorfs.FindORFS
Starting Task = validate.VALIDATE
    Job  = [[soapdenovo.55.faa] -> [validate.ok]] completed
Completed Task = validate.Validate
Starting Task = findrepeats.FINDREPEATS
    Job  = [proba.fna -> proba.repeats] completed
Completed Task = findreps.FindRepeats
Starting Task = annotate.ANNOTATE
    Job  = [proba.faa -> proba.hits] completed
Completed Task = annotate.Annotate
Starting Task = functionalannotation.FUNCTIONALANNOTATION
    Job  = [proba.faa -> [blast.out, krona.ec.input]] completed
Completed Task = fannotate.FunctionalAnnotation
Starting Task = scaffold.SCAFFOLD
    Job  = [[proba.asm.contig] -> scaffold.ok] completed
Completed Task = scaffold.Scaffold
Starting Task = findscaffoldorfs.FINDSCAFFOLDORFS
    Job  = [proba.linearize.scaffolds.final -> proba.fna] completed
Completed Task = findscforfs.FindScaffoldORFS
Starting Task = abundance.ABUNDANCE
    Job  = [proba.asm.contig -> proba.taxprof.pct.txt] completed
Completed Task = abundance.Abundance
Starting Task = propagate.PROPAGATE
    Job  = [proba.annots -> propagate.ok] completed
Completed Task = propagate.Propagate
Starting Task = classify.CLASSIFY
    Job  = [proba.clusters -> classify.ok] completed
Completed Task = classify.Classify
Starting Task = postprocess.POSTPROCESS
Oops, MetAMOS finished with errors! see text in red above for details.
```

```
[root@tcmc_sandbox2 Test]# cd ..
[root@tcmc_sandbox2 metAMOS-1.5rc3]# python INSTALL.py core
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Selected to install workflowName: OPTIONAL.
Will automatically install:
        Fcp
        Pysam
        Setuptools
        Phylosift
        Fastqc
        Matplotlib
        Metavelvet
        Lap
        Metaphyler
        Kronatools
        Cython
        Sra
        Velvet
        Velvet-Sc
        Kraken
        Psutil
        Uniprot
        Amos
        Numpy
        Phmmer
Checking whether refseq_protein is complete. Expecting 27 partitions.

Run setup.py..
running install_scripts
running egg_info
writing metAMOS.egg-info/PKG-INFO
writing top-level names to metAMOS.egg-info/top_level.txt
writing dependency_links to metAMOS.egg-info/dependency_links.txt
reading manifest file 'metAMOS.egg-info/SOURCES.txt'
writing manifest file 'metAMOS.egg-info/SOURCES.txt'
running build_scripts
copying build/scripts-2.7/runPipeline.py -> /home/AnalysisTools/metAMOS-1.5rc3
copying build/scripts-2.7/initPipeline.py -> /home/AnalysisTools/metAMOS-1.5rc3
changing mode of /home/AnalysisTools/metAMOS-1.5rc3/runPipeline.py to 755
changing mode of /home/AnalysisTools/metAMOS-1.5rc3/initPipeline.py to 755
running build_ext
skipping './src/preprocess.c' Cython extension (up-to-date)
skipping './src/annotate.c' Cython extension (up-to-date)
skipping './src/fannotate.c' Cython extension (up-to-date)
skipping './src/mapreads.c' Cython extension (up-to-date)
skipping './src/findorfs.c' Cython extension (up-to-date)
skipping './src/findscforfs.c' Cython extension (up-to-date)
skipping './src/scaffold.c' Cython extension (up-to-date)
[root@tcmc_sandbox2 metAMOS-1.5rc3]# python INSTALL.py optional
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Selected to install workflowName: OPTIONAL.
Will automatically install:
        Fcp
        Pysam
        Setuptools
        Phylosift
        Fastqc
        Matplotlib
        Metavelvet
        Lap
        Metaphyler
        Kronatools
        Cython
        Sra
        Velvet
        Velvet-Sc
        Kraken
        Psutil
        Uniprot
        Amos
        Numpy
        Phmmer
Checking whether refseq_protein is complete. Expecting 27 partitions.

Run setup.py..
running install_scripts
running egg_info
writing metAMOS.egg-info/PKG-INFO
writing top-level names to metAMOS.egg-info/top_level.txt
writing dependency_links to metAMOS.egg-info/dependency_links.txt
reading manifest file 'metAMOS.egg-info/SOURCES.txt'
writing manifest file 'metAMOS.egg-info/SOURCES.txt'
running build_scripts
copying build/scripts-2.7/runPipeline.py -> /home/AnalysisTools/metAMOS-1.5rc3
copying build/scripts-2.7/initPipeline.py -> /home/AnalysisTools/metAMOS-1.5rc3
changing mode of /home/AnalysisTools/metAMOS-1.5rc3/runPipeline.py to 755
changing mode of /home/AnalysisTools/metAMOS-1.5rc3/initPipeline.py to 755
running build_ext
skipping './src/preprocess.c' Cython extension (up-to-date)
skipping './src/annotate.c' Cython extension (up-to-date)
skipping './src/fannotate.c' Cython extension (up-to-date)
skipping './src/mapreads.c' Cython extension (up-to-date)
skipping './src/findorfs.c' Cython extension (up-to-date)
skipping './src/findscforfs.c' Cython extension (up-to-date)
skipping './src/scaffold.c' Cython extension (up-to-date)
```

```
[root@tcmc_sandbox2 metAMOS-1.5rc3]# python INSTALL.py iMetAMOS
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Selected to install workflowName: OPTIONAL.
Selected to install workflowName: IMETAMOS.
Will automatically install:
        Pysam
        Fastqc
        Ca
        Ale
        Sga
        Velvet-Sc
        Metaphyler
        Phylosift
        Metavelvet
        Velvet
        Soap2
        Frcbam
        Quast
        Eautils
        Ray
        Numpy
        Freebayes
        Fcp
        Edena
        Uniprot
        Cython
        Cgal
        Mira
        Matplotlib
        Prokka
        Idba
        Cmake
        Lap
        Masurca
        Kronatools
        Abyss
        Sra
        Spades
        Kraken
        Psutil
        Setuptools
        Amos
        Phmmer
        Kmergenie
        Reapr
Checking whether refseq_protein is complete. Expecting 27 partitions.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to cbcb.umd.edu:21; No route to host
unzip:  cannot find or open frcbam.zip, frcbam.zip.zip or frcbam.zip.ZIP.
mv: cannot stat âFRC_align-3398ca469b2077d6672b85317eee6fea171b6a27â: No such file or directory
Traceback (most recent call last):
  File "INSTALL.py", line 1678, in <module>
    os.chdir("./Utilities/cpp/%s%s-%s%sFRCbam/src/samtools"%(os.sep, OSTYPE, MACHINETYPE, os.sep))
OSError: [Errno 2] No such file or directory: './Utilities/cpp//Linux-x86_64/FRCbam/src/samtools'
*****************************
```

here is what the POSTPROCESS.log file shows in the /Test/test/ directory:

```
ln: failed to create symbolic link ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/proba.bnk’: File exists
ln: failed to create hard link ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/proba.orf.fna’: File exists
ln: failed to create hard link ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/proba.orf.faa’: File exists
ln: failed to create hard link ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/proba.scf.orf.fna’: File exists
ln: failed to create hard link ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/proba.scf.orf.faa’: File exists
unlink: cannot unlink ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/html’: Is a directory
mkdir: cannot create directory ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/html’: File exists
mv: cannot stat ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Preprocess/out/*.fastqc’: No such file or directory
unlink: cannot unlink ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/Postprocess/out/html/FunctionalAnnotation.html’: No such file or directory
ln: failed to access ‘/home/AnalysisTools/metAMOS-1.5rc3/Test/test1/FunctionalAnnotation/out/ec.krona.html’: No such file or directory
```

**Comment by skoren** [comment]
1) I HAVE definitely installed MetaGeneMark, REAPR and FRC_Align I've included the executable (and bin directories) in PATH but the test scrip still cannot find them.

The pipeline is just calling which <command> so if it is in the path they should be found. For MetaGeneMark it is looking for gmhmmp, for Reapr it is looking for reapr, and for FRC it is looking for FRCbam. You can also add a symlink from the Utilities/cpp/Linux-amd64 folder to the tools. It would be FRCBam to your FRC install folder, REAPR to your reapr install folder, and gmhmmp binary for MetaGeneMark. I think it should be using `which FRC` not `which FRCbam` so that is a bug.

2) I'm not sure why the test stopped abruptly at POSTPROCESSING.
This is probably the same as issue #248. You can change the script to add the verbose (-v) option to runPipeline to verify.

3) How can I re-run the test pipeline cleanly ?
Rerunning the same command will resume the pipeline at the failed step, if you want to re-run from scratch you can remove the test1 folder.

**Comment by SabeenR** [comment]
Thanks for your reply Sergey,
I was able to get rid of the FRCbam warning by changing the call for FRC instead of FRCbam in the runPipeline.sh file and by creating  a symbolic link to gmhmmp binany as you suggested but I'm still unable to get rid of the REAPR warning.

Here is the ls -l for the REAPR directory inside /metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/
[root@tcmc_sandbox2 REAPR]# ls -l
total 388
-rw-r--r--. 1 12654 1054   5383 Feb 23  2015 changelog.txt
-rwxr-xr-x. 1 12654 1054   4356 Feb 23  2015 install.sh
-rw-r--r--. 1 12654 1054  35147 Feb 23  2015 licence.txt
-rw-r--r--. 1 12654 1054 325751 Feb 23  2015 manual.pdf
-rw-r--r--. 1 1 12654 1054   2854 Feb 23  2015 README
lrwxrwxrwx. 1 root  root     80 Sep 28 09:28 reapr.pl -> /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/REAPR/src/reapr.pl
drwxr-xr-x. 2 12654 1054   4096 Sep 28 09:27 src
drwxr-xr-x. 7 12654 1054   4096 Mar 17  2014 third_party

**Also, inside the src dir:**

[root@tcmc_sandbox2 REAPR]# ls -l src
total 4396
-rwxr-xr-x. 1 root  root 339444 Sep 27 13:26 bam2fcdEstimate
-rw-r--r--. 1 12654 1054   5976 Jan  3  2013 bam2fcdEstimate.cpp
-rw-r--r--. 1 root  root  58120 Sep 27 13:26 bam2fcdEstimate.o
-rwxr-xr-x. 1 root  root 297786 Sep 27 13:26 bam2fragCov
-rw-r--r--. 1 12654 1054   6027 Mar 13  2014 bam2fragCov.cpp
-rw-r--r--. 1 root  root  46888 Sep 27 13:26 bam2fragCov.o
-rwxr-xr-x. 1 root  root 316232 Sep 27 13:26 bam2insert
-rw-r--r--. 1 12654 1054   5358 Mar 13  2014 bam2insert.cpp
-rw-r--r--. 1 root  root  38840 Sep 27 13:26 bam2insert.o
-rwxr-xr-x. 1 root  root 298034 Sep 27 13:26 bam2perfect
-rw-r--r--. 1 12654 1054   6697 Sep  5  2012 bam2perfect.cpp
-rw-r--r--. 1 root  root  52136 Sep 27 13:26 bam2perfect.o
lrwxrwxrwx. 1 12654 1054     23 Jan  3  2013 bamtools -> ../third_party/bamtools
-rw-r--r--. 1 12654 1054    650 Jul 23  2012 coveragePlot.cpp
-rw-r--r--. 1 12654 1054    755 Jul 23  2012 coveragePlot.h
-rw-r--r--. 1 root  root  18072 Sep 27 13:26 coveragePlot.o
-rw-r--r--. 1 12654 1054   1329 Jul 23  2012 errorWindow.cpp
-rw-r--r--. 1 12654 1054   1175 Jul 23  2012 errorWindow.h
-rw-r--r--. 1 root  root   9504 Sep 27 13:26 errorWindow.o
-rwxr-xr-x. 1 root  root  20654 Sep 27 13:26 fa2gaps
-rw-r--r--. 1 12654 1054    947 Jul 23  2012 fa2gaps.cpp
-rw-r--r--. 1 root  root   5904 Sep 27 13:26 fa2gaps.o
-rwxr-xr-x. 1 root  root  25186 Sep 27 13:26 fa2gc
-rw-r--r--. 1 12654 1054   5749 Feb 26  2014 fa2gc.cpp
-rw-r--r--. 1 root  root  12432 Sep 27 13:26 fa2gc.o
-rw-r--r--. 1 12654 1054   2781 Nov  6  2012 fasta.cpp
-rw-r--r--. 1 12654 1054   1371 Nov  6  2012 fasta.h
-rw-r--r--. 1 root  root  12712 Sep 27 13:26 fasta.o
lrwxrwxrwx. 1 12654 1054     38 Jan  3  2013 findknownsnps -> ../third_party/snpomatic/findknownsnps
-rw-r--r--. 1 12654 1054  10022 Jan  3  2013 histogram.cpp
-rw-r--r--. 1 12654 1054   3129 Aug 14  2012 histogram.h
-rw-r--r--. 1 root  root  46816 Sep 27 13:26 histogram.o
lrwxrwxrwx. 1 root  root     80 Sep 28 09:26 Link to reapr.pl -> /home/AnalysisTools/metAMOS-1.5rc3/Utilities/cpp/Linux-x86_64/REAPR/src/reapr.pl
-rw-r--r--. 1 12654 1054   4016 Mar 13  2014 Makefile
-rwxr-xr-x. 1 root  root  39859 Sep 27 13:26 make_plots
-rw-r--r--. 1 12654 1054   3527 Mar  8  2013 make_plots.cpp
-rw-r--r--. 1 root  root  45112 Sep 27 13:26 make_plots.o
-rwxr-xr-x. 1 root  root  34698 Sep 27 13:26 n50
-rw-r--r--. 1 12654 1054   4181 Nov  8  2012 n50.cpp
-rw-r--r--. 1 root  root  21880 Sep 27 13:26 n50.o
-rwxr-xr-x. 1 12654 1054   3587 Feb 23  2015 reapr.pl
lrwxrwxrwx. 1 12654 1054     32 Jan  3  2013 samtools -> ../third_party/samtools/samtools
-rwxr-xr-x. 1 root  root  30368 Sep 27 13:26 scaff2contig
-rwxr-xr-x. 1 12654 1054   2273 Jul 23  2012 scaff2contig.cpp
-rw-r--r--. 1 root  root  18416 Sep 27 13:26 scaff2contig.o
lrwxrwxrwx. 1 12654 1054     27 Apr  5  2013 smalt -> ../third_party/smalt_x86_64
lrwxrwxrwx. 1 12654 1054     20 Jan  3  2013 tabix -> ../third_party/tabix
-rwxr-xr-x. 1 root  root 310907 Sep 27 13:26 task_break
-rw-r--r--. 1 12654 1054  15915 Feb 23  2015 task_break.cpp
-rw-r--r--. 1 root  root  65912 Sep 27 13:26 task_break.o
-rwxr-xr-x. 1 12654 1054   2461 Feb 24  2014 task_facheck.pl
-rwxr-xr-x. 1 root  root 319052 Sep 27 13:26 task_fcdrate
-rw-r--r--. 1 12654 1054  11614 Jul 23  2012 task_fcdrate.cpp
-rw-r--r--. 1 root  root  49296 Sep 27 13:26 task_fcdrate.o
-rwxr-xr-x. 1 root  root 312835 Sep 27 13:26 task_gapresize
-rw-r--r--. 1 12654 1054   7622 Mar 13  2014 task_gapresize.cpp
-rw-r--r--. 1 root  root  40384 Sep 27 13:26 task_gapresize.o
-rwxr-xr-x. 1 12654 1054   6122 Apr  5  2013 task_perfectfrombam.pl
-rwxr-xr-x. 1 12654 1054   4619 Nov 15  2012 task_perfectmap.pl
-rwxr-xr-x. 1 12654 1054   4097 Feb 23  2015 task_pipeline.pl
-rwxr-xr-x. 1 12654 1054   3158 Mar  8  2013 task_plots.pl
-rwxr-xr-x. 1 12654 1054  14916 Jul 18  2014 task_preprocess.pl
-rwxr-xr-x. 1 root  root 417075 Sep 27 13:26 task_score
-rw-r--r--. 1 12654 1054  41444 Mar 13  2014 task_score.cpp
-rw-r--r--. 1 root  root 212160 Sep 27 13:26 task_score.o
-rwxr-xr-x. 1 12654 1054   1410 Feb 24  2014 task_seqrename.pl
-rwxr-xr-x. 1 12654 1054   5576 Mar 13  2014 task_smaltmap.pl
-rwxr-xr-x. 1 root  root 384509 Sep 27 13:26 task_stats
-rw-r--r--. 1 12654 1054  33174 Mar 13  2014 task_stats.cpp
-rw-r--r--. 1 root  root 127520 Sep 27 13:26 task_stats.o
-rwxr-xr-x. 1 12654 1054   8928 Nov  8  2012 task_summary.pl
-rw-r--r--. 1 12654 1054  11461 Jan  3  2013 trianglePlot.cpp
-rw-r--r--. 1 12654 1054   3157 Jul 23  2012 trianglePlot.h
-rw-r--r--. 1 root  root  28440 Sep 27 13:26 trianglePlot.o
-rw-r--r--. 1 12654 1054   2379 Jul 23  2012 utils.cpp
-rw-r--r--. 1 12654 1054   1561 Jul 23  2012 utils.h
-rw-r--r--. 1 root  root  40232 Sep 27 13:26 utils.o

**Comment by skoren** [comment]
REAPR cannot be found because your install looks incomplete or is a different version (metAMOS uses 1.0.16). The installation should add a symlink named reapr pointing to reapr.pl:

```
$ tail -n 20 install.sh
------------------------------------------------------------------------------
"
cd $rootdir/src
make
cd ..
ln -s src/reapr.pl reapr
echo "
Reapr compiled

All done!

Run
./reapr
for usage.

Read the manual
manual.pdf
for full instructions
"


```

This is what metAMOS is looking for and not finding.

**Comment by SabeenR** [comment]
Aah.. I have a different version – I have 1.0.18

Not sure how to uninstall it and install a clean copy of 1.0.16

Any suggestions ?

Thanks so much for your help.

**Comment by skoren** [comment]
You can try symlinking src/reapr.pl as reapr or just renaming reapr.pl to reapr since it is already a symlink in your folder.

**Comment by SabeenR** [comment]
IT WORKED!! Now it find reapr !

Ok now we need to tackle the next issue.

Ive just opened another ticket #250

Not sure why it suddenly stops at the FINDORFs stage.. didn't do that before.

I've removed the -a soap flag from the run_pipline_test.sh and re-running it now.

Same error :(
Not sure why it didn't go thru like before.

Sabeen

-------- Original message --------
