### ISSUE TITLE
psutil source path error in INSTALL.py

### ISSUE THREAD

**Issue by milw** [marbl/metAMOS#251]
It seems the Google link for psutil-0.6.1.tar.gz is no longer valid- I replaced

 with this link and got INSTALL.py to work:
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/psutil/psutil-0.6.1.tar.gz

(old nonfunctional link is http://psutil.googlecode.com/files/psutil-0.6.1.tar.gz)
[INSTALL.py.txt](https://github.com/marbl/metAMOS/files/517129/INSTALL.py.txt)

**Comment by skoren** [comment]
This was fixed in a recent commit
