### ISSUE TITLE
Paths are invalid for install

### ISSUE THREAD

**Issue by ianmisner** [marbl/metAMOS#252]
Hello,

It seems that a lot of the paths in the INSTALL.py script are invalid. I've tried to manually find and update the paths but now I'm not convinced that this has installed properly. Are there any new version s available with updated paths for install?

**Comment by skoren** [comment]
The latest code in the repo for the 1.5rc3 branch (so you have to pull from github not download the release) should have corrected paths (I just fixed a few more). In general if a tool wasn't installed properly the pipeline will fail so you can try running either some of the provided examples in Test or your own dataset to see if the tools are properly installed.

If there are other paths broken in the latest code that you have fix, can you make a pull request?

**Comment by ianmisner** [comment]
[INSTALL.py.txt](https://github.com/marbl/metAMOS/files/558318/INSTALL.py.txt)

Here is my install script. I had to make a few comments to get this working and like I said I'm not sure it's running properly. When I get my results for example the Browse results tab on the summary.html is blank while the rest of the pipeline seems to be working well enough.

**Comment by skoren** [comment]
These should be fixed in the latest 1.5rc3 branch.
