### ISSUE TITLE
RHEL 6.8 Install Issue.

### ISSUE THREAD

**Issue by DownSouthSmartGuy** [marbl/metAMOS#253]
I pulled down metAMOS and I am trying to install for one of our researchers, and get the following output.

[root@LabStation05 metAMOS-1.5rc3]# python INSTALL.py core
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Will automatically install:
        Pysam
        Setuptools
        Fastqc
        Matplotlib
        Metavelvet
        Lap
        Kronatools
        Cython
        Sra
        Velvet
        Velvet-Sc
        Kraken
        Psutil
        Uniprot
        Amos
        Numpy
MetAMOS would like to record anonymous usage statistics, is this ok ?
Enter Y/N: Y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
105  1586  105  1586    0     0  45192      0 --:--:-- --:--:-- --:--:--  172k

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat `./Utilities/python/psutil-0.6.1': No such file or directory
Traceback (most recent call last):
  File "INSTALL.py", line 298, in <module>
    os.chdir("./Utilities/python/psutil")
OSError: [Errno 2] No such file or directory: './Utilities/python/psutil'

Can anyone provide any assistance or point me in the right direction to solve this issue?

Thanks in advance.

MJ

**Comment by skoren** [comment]
This should be fixed if you pull the latest v1.5rc3 from github.
