### ISSUE TITLE
Run setup.py import error

### ISSUE THREAD

**Issue by GLFR** [marbl/metAMOS#261]
Hello,

I've tried to install metAMOS version 1.5rc3 a couple of times and I keep getting the following error:

Run setup.py..
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
mv: cannot stat ‘runPipeline.py’: No such file or directory
mv: cannot stat ‘initPipeline.py’: No such file or directory

I followed the installation process using the commands on "Read the Docs" so I'm not sure how these files are missing? 

Many thanks for your help

**Comment by skoren** [comment]
It sounds like the cython build as part of metAMOS did not work, it should be in the log output from INSTALL.py. You could also install cython yourself on the system in which case metAMOS will use the systemwide cython instead of trying to build it.

**Comment by skoren** [comment]
Closing, inactivity.
