### ISSUE TITLE
rm: cannot remove `~/all.seq.mates': No such file or directory

### ISSUE THREAD

**Issue by chen496** [marbl/metAMOS#264]
Hi, I have a question that when I run the command without -t eautils, it shows the error following: 
my file is single and without adapters. if I add the -t option it does not show any problems.

../initPipeline -f -1 51GHLH2.fa -d test2 
../runPipeline -a mira -c fcp -g fraggenescan -y -p 16 -d test2 -v

The PROCESS.log:
Picked up _JAVA_OPTIONS: -Xmx512m
rm: cannot remove `/nethome/cxw496/software/src/metAMOS-1.5rc3/chen/test2/Preprocess/out/all.seq.mates': No such file or directory

The error:

Starting Task = preprocess.PREPROCESS
*** metAMOS running command: java -cp /nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/java:.:. outputDefaultQuality /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/test2/Preprocess/in/51GHLH2.fa > /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/test2/Preprocess/in/51GHLH2.fa.qual

*** metAMOS running command: rm /nethome/cxw496/software/src/metAMOS-1.5rc3/chen/test2/Preprocess/out/all.seq.mates

Read file corrupted, please fix and restart!
Oops, MetAMOS finished with errors! see text in red above for details.
Traceback (most recent call last):
  File "../runPipeline", line 991, in <module>
    verbose = 1)
  File "/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 2965, in pipeline_run
    raise job_errors
RethrownJobError: 
    
    
    
    Exception #1
      'exceptions.SystemExit(1)' raised in ...
       Task = def preprocess.Preprocess(...):
       Job  = [[51GHLH2.fa] -> preprocess.success]
Traceback (most recent call last):
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 625, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/Utilities/ruffus/task.py", line 491, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "/nethome/cxw496/software/src/metAMOS-1.5rc3/src/preprocess.py", line 536, in Preprocess
        sys.exit(1)
    SystemExit: 1

Thanks 
Chen

**Comment by skoren** [comment]
I think there is a bug in processing unpaired fasta reads, comment out lines 534-536 and it should work.
```
534 #                   if len(reads) % 2 != 0:
535 #                       print "Read file corrupted, please fix and restart!"
536 #                       sys.exit(1)
```

**Comment by chen496** [comment]
OK, Thank you very much
