### ISSUE TITLE
python INSTALL.py error

### ISSUE THREAD

**Issue by bioinformaticspcj** [marbl/metAMOS#277]
when I try to install metAMOS with INSTALL.py, an error occured as follows:
<utils.Settings instance at 0x7fa95228a998>
['svmem(total=355574743040L', ' available=333131087872L', ' percent=6.3', ' used=25075109888L', ' free=330499633152L', ' active=19914387456', ' inactive=2556784640', ' buffers=35610624L', ' cached=2595844096)']
Traceback (most recent call last):
  File "INSTALL.py", line 515, in <module>
    mem = utils.getAvailableMemory(settings)
  File "/data/project/tools/metagenome/metAMOS-1.5rc3/src/utils.py", line 1286, in getAvailableMemory
    freemem = long(memusage[2].split("free=")[-1])+long(cacheusage)
ValueError: invalid literal for long() with base 10: ' percent=6.3'

I do not know why this would happen, does anyone know how to fix it ?

**Comment by skoren** [comment]
You most likely have an incompatible version of psutil installed. metAMOS is tested with version 0.6.1. If you have a newer one, remove it from your python path and let metAMOS install/use its own version.
